# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AbilityChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AbilityControlBlock_pb2 as AbilityControlBlock__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x41\x62ilityChangeNotify.proto\x1a\x19\x41\x62ilityControlBlock.proto\"]\n\x13\x41\x62ilityChangeNotify\x12\x33\n\x15\x61\x62ility_control_block\x18\x0c \x01(\x0b\x32\x14.AbilityControlBlock\x12\x11\n\tentity_id\x18\x02 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AbilityChangeNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_ABILITYCHANGENOTIFY']._serialized_start=56
  _globals['_ABILITYCHANGENOTIFY']._serialized_end=149
# @@protoc_insertion_point(module_scope)
