# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AchievementAllDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Achievement_pb2 as Achievement__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x41\x63hievementAllDataNotify.proto\x1a\x11\x41\x63hievement.proto\"e\n\x18\x41\x63hievementAllDataNotify\x12&\n\x10\x61\x63hievement_list\x18\x0f \x03(\x0b\x32\x0c.Achievement\x12!\n\x19reward_taken_goal_id_list\x18\x04 \x03(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AchievementAllDataNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_ACHIEVEMENTALLDATANOTIFY']._serialized_start=53
  _globals['_ACHIEVEMENTALLDATANOTIFY']._serialized_end=154
# @@protoc_insertion_point(module_scope)
