# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Achievement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Status_pb2 as Status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41\x63hievement.proto\x1a\x0cStatus.proto\"w\n\x0b\x41\x63hievement\x12\x13\n\x0b\x63urProgress\x18\n \x01(\r\x12\n\n\x02id\x18\r \x01(\r\x12\x15\n\rtotalProgress\x18\x0e \x01(\r\x12\x17\n\x06status\x18\x05 \x01(\x0e\x32\x07.Status\x12\x17\n\x0f\x66inishTimestamp\x18\x06 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Achievement_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ACHIEVEMENT']._serialized_start=35
  _globals['_ACHIEVEMENT']._serialized_end=154
# @@protoc_insertion_point(module_scope)
