# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityPushTipsInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ActivityPushTipsData_pb2 as ActivityPushTipsData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ActivityPushTipsInfoNotify.proto\x1a\x1a\x41\x63tivityPushTipsData.proto\"}\n\x1a\x41\x63tivityPushTipsInfoNotify\x12\x12\n\nscheduleId\x18\x06 \x01(\r\x12\x37\n\x18\x61\x63tivityPushTipsDataList\x18\x07 \x03(\x0b\x32\x15.ActivityPushTipsData\x12\x12\n\nactivityId\x18\t \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityPushTipsInfoNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ACTIVITYPUSHTIPSINFONOTIFY']._serialized_start=64
  _globals['_ACTIVITYPUSHTIPSINFONOTIFY']._serialized_end=189
# @@protoc_insertion_point(module_scope)
