# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityAcceptAllGiveGiftRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ActivityAcceptGiftResultInfo_pb2 as ActivityAcceptGiftResultInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ActivityAcceptAllGiveGiftRsp.proto\x1a\"ActivityAcceptGiftResultInfo.proto\"\x84\x01\n\x1c\x41\x63tivityAcceptAllGiveGiftRsp\x12\x12\n\nscheduleId\x18\x0f \x01(\r\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x12?\n\x18\x61\x63\x63\x65ptGiftResultInfoList\x18\x0e \x03(\x0b\x32\x1d.ActivityAcceptGiftResultInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityAcceptAllGiveGiftRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ACTIVITYACCEPTALLGIVEGIFTRSP']._serialized_start=75
  _globals['_ACTIVITYACCEPTALLGIVEGIFTRSP']._serialized_end=207
# @@protoc_insertion_point(module_scope)
