# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityGetCanGiveFriendGiftRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ActivityGetCanGiveFriendGiftRsp.proto\"\xc2\x01\n\x1f\x41\x63tivityGetCanGiveFriendGiftRsp\x12\x13\n\x0bschedule_id\x18\x07 \x01(\r\x12\x46\n\x0cgift_num_map\x18\t \x03(\x0b\x32\x30.ActivityGetCanGiveFriendGiftRsp.GiftNumMapEntry\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x1a\x31\n\x0fGiftNumMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivityGetCanGiveFriendGiftRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _ACTIVITYGETCANGIVEFRIENDGIFTRSP_GIFTNUMMAPENTRY._options = None
  _ACTIVITYGETCANGIVEFRIENDGIFTRSP_GIFTNUMMAPENTRY._serialized_options = b'8\001'
  _globals['_ACTIVITYGETCANGIVEFRIENDGIFTRSP']._serialized_start=42
  _globals['_ACTIVITYGETCANGIVEFRIENDGIFTRSP']._serialized_end=236
  _globals['_ACTIVITYGETCANGIVEFRIENDGIFTRSP_GIFTNUMMAPENTRY']._serialized_start=187
  _globals['_ACTIVITYGETCANGIVEFRIENDGIFTRSP_GIFTNUMMAPENTRY']._serialized_end=236
# @@protoc_insertion_point(module_scope)
