# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddBlacklistRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendBrief_pb2 as FriendBrief__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41\x64\x64\x42lacklistRsp.proto\x1a\x11\x46riendBrief.proto\"M\n\x0f\x41\x64\x64\x42lacklistRsp\x12\x0f\n\x07retcode\x18\x06 \x01(\x05\x12)\n\x13target_friend_brief\x18\x01 \x01(\x0b\x32\x0c.FriendBriefB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AddBlacklistRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_ADDBLACKLISTRSP']._serialized_start=44
  _globals['_ADDBLACKLISTRSP']._serialized_end=121
# @@protoc_insertion_point(module_scope)
