# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddNoGachaAvatarCardNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AddNoGachaAvatarCardTransferItem_pb2 as AddNoGachaAvatarCardTransferItem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n AddNoGachaAvatarCardNotify.proto\x1a&AddNoGachaAvatarCardTransferItem.proto\"\xd6\x01\n\x1a\x41\x64\x64NoGachaAvatarCardNotify\x12\x0e\n\x06reason\x18\x03 \x01(\r\x12\x13\n\x0b\x41IGPMLAPMBL\x18\x0e \x01(\r\x12\x0f\n\x07item_id\x18\x0f \x01(\r\x12\x11\n\tavatar_id\x18\x01 \x01(\r\x12\x13\n\x0bKNGMKKHPDBJ\x18\x04 \x01(\r\x12\x1b\n\x13is_transfer_to_item\x18\t \x01(\x08\x12=\n\x12transfer_item_list\x18\x06 \x03(\x0b\x32!.AddNoGachaAvatarCardTransferItemB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AddNoGachaAvatarCardNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_ADDNOGACHAAVATARCARDNOTIFY']._serialized_start=77
  _globals['_ADDNOGACHAAVATARCARDNOTIFY']._serialized_end=291
# @@protoc_insertion_point(module_scope)
