# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AFLCCHIGHFC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import KIEHIGCKOHO_pb2 as KIEHIGCKOHO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41\x46LCCHIGHFC.proto\x1a\x11KIEHIGCKOHO.proto\"\x84\x01\n\x0b\x41\x46LCCHIGHFC\x12\x13\n\x0b\x66\x65kdaediiel\x18\x01 \x01(\x05\x12\x13\n\x0bocjodgafcna\x18\x02 \x01(\x05\x12\x13\n\x0bpaamjmeflfp\x18\x03 \x01(\x05\x12\x13\n\x0blolngckkkek\x18\x04 \x01(\x05\x12!\n\x0bnkifjffiglb\x18\x05 \x03(\x0b\x32\x0c.KIEHIGCKOHOB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AFLCCHIGHFC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_AFLCCHIGHFC']._serialized_start=41
  _globals['_AFLCCHIGHFC']._serialized_end=173
# @@protoc_insertion_point(module_scope)
