# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AIHKOACHDJH.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ExhibitionDisplayInfo_pb2 as ExhibitionDisplayInfo__pb2
import IELKGAMFOLN_pb2 as IELKGAMFOLN__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41IHKOACHDJH.proto\x1a\x1b\x45xhibitionDisplayInfo.proto\x1a\x11IELKGAMFOLN.proto\"\xe8\x01\n\x0b\x41IHKOACHDJH\x12)\n\tscoreList\x18\x0e \x03(\x0b\x32\x16.ExhibitionDisplayInfo\x12\x10\n\x08\x64uration\x18\n \x01(\r\x12\x11\n\tbeginTime\x18\x0b \x01(\r\x12\x11\n\tstageType\x18\x05 \x01(\r\x12\x13\n\x0bggihgakpekk\x18\t \x03(\r\x12\x11\n\tplayIndex\x18\x0c \x01(\r\x12\x13\n\x0bmdpgfcplekf\x18\r \x01(\x08\x12$\n\x0esettleInfoList\x18\x07 \x03(\x0b\x32\x0c.IELKGAMFOLN\x12\x13\n\x0bpdminbppnje\x18\x03 \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AIHKOACHDJH_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_AIHKOACHDJH']._serialized_start=70
  _globals['_AIHKOACHDJH']._serialized_end=302
# @@protoc_insertion_point(module_scope)
