# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AllWidgetBackgroundActiveStateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*AllWidgetBackgroundActiveStateNotify.proto\"M\n$AllWidgetBackgroundActiveStateNotify\x12%\n\x1d\x62\x61\x63kground_active_widget_list\x18\x0c \x03(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AllWidgetBackgroundActiveStateNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_ALLWIDGETBACKGROUNDACTIVESTATENOTIFY']._serialized_start=46
  _globals['_ALLWIDGETBACKGROUNDACTIVESTATENOTIFY']._serialized_end=123
# @@protoc_insertion_point(module_scope)
