# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AllWidgetDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SkyCrystalDetectorData_pb2 as SkyCrystalDetectorData__pb2
import WeatherWizardData_pb2 as WeatherWizardData__pb2
import LunchBoxData_pb2 as LunchBoxData__pb2
import WidgetCoolDownData_pb2 as WidgetCoolDownData__pb2
import WidgetSlotData_pb2 as WidgetSlotData__pb2
import AnchorPointData_pb2 as AnchorPointData__pb2
import ClientCollectorData_pb2 as ClientCollectorData__pb2
import DetectorData_pb2 as DetectorData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x41llWidgetDataNotify.proto\x1a\x1cSkyCrystalDetectorData.proto\x1a\x17WeatherWizardData.proto\x1a\x12LunchBoxData.proto\x1a\x18WidgetCoolDownData.proto\x1a\x14WidgetSlotData.proto\x1a\x15\x41nchorPointData.proto\x1a\x19\x43lientCollectorData.proto\x1a\x12\x44\x65tectorData.proto\"\x91\x04\n\x13\x41llWidgetDataNotify\x12\x37\n\x16skyCrystalDetectorData\x18\x02 \x01(\x0b\x32\x17.SkyCrystalDetectorData\x12\x33\n\x16normalCoolDownDataList\x18\x04 \x03(\x0b\x32\x13.WidgetCoolDownData\x12!\n\x08slotList\x18\x0e \x03(\x0b\x32\x0f.WidgetSlotData\x12\"\n\x1a\x62\x61\x63kgroundActiveWidgetList\x18\x05 \x03(\r\x12)\n\x0f\x61nchorPointList\x18\x0b \x03(\x0b\x32\x10.AnchorPointData\x12-\n\x11weatherWizardData\x18\r \x01(\x0b\x32\x12.WeatherWizardData\x12!\n\x19nextAnchorPointUsableTime\x18\x0f \x01(\r\x12\x35\n\x17\x63lientCollectorDataList\x18\x07 \x03(\x0b\x32\x14.ClientCollectorData\x12\x32\n\x15\x63oolDownGroupDataList\x18\x06 \x03(\x0b\x32\x13.WidgetCoolDownData\x12\x38\n!oneoffGatherPointDetectorDataList\x18\x08 \x03(\x0b\x32\r.DetectorData\x12#\n\x0clunchBoxData\x18\x01 \x01(\x0b\x32\r.LunchBoxDataB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AllWidgetDataNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ALLWIDGETDATANOTIFY']._serialized_start=223
  _globals['_ALLWIDGETDATANOTIFY']._serialized_end=752
# @@protoc_insertion_point(module_scope)
