# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AnchorPointOpRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x41nchorPointOpRsp.proto\"Z\n\x10\x41nchorPointOpRsp\x12\x0f\n\x07retcode\x18\x05 \x01(\x05\x12\x1c\n\x14\x61nchor_point_op_type\x18\r \x01(\r\x12\x17\n\x0f\x61nchor_point_id\x18\n \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AnchorPointOpRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_ANCHORPOINTOPRSP']._serialized_start=26
  _globals['_ANCHORPOINTOPRSP']._serialized_end=116
# @@protoc_insertion_point(module_scope)
