# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ANOKFBLCGGM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PDOPJIGDNPF_pb2 as PDOPJIGDNPF__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41NOKFBLCGGM.proto\x1a\x11PDOPJIGDNPF.proto\"h\n\x0b\x41NOKFBLCGGM\x12\x10\n\x08moduleId\x18\x01 \x01(\r\x12\x0f\n\x07sceneId\x18\x02 \x01(\r\x12\x13\n\x0bhoogfkfbckk\x18\x03 \x01(\x08\x12!\n\x0blpjicbgaldo\x18\x04 \x03(\x0b\x32\x0c.PDOPJIGDNPFB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ANOKFBLCGGM_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ANOKFBLCGGM']._serialized_start=40
  _globals['_ANOKFBLCGGM']._serialized_end=144
# @@protoc_insertion_point(module_scope)
