# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AOHEFFCPELI.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DOINBFHLBHP_pb2 as DOINBFHLBHP__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41OHEFFCPELI.proto\x1a\x11\x44OINBFHLBHP.proto\"p\n\x0b\x41OHEFFCPELI\x12\x15\n\rcontroller_id\x18\x0b \x01(\r\x12\x12\n\nbegin_time\x18\x05 \x01(\x04\x12\x13\n\x0bOAKPHGNDJLO\x18\x0c \x01(\x04\x12!\n\x0bJFFMMIKBICI\x18\x0e \x01(\x0e\x32\x0c.DOINBFHLBHPB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AOHEFFCPELI_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_AOHEFFCPELI']._serialized_start=40
  _globals['_AOHEFFCPELI']._serialized_end=152
# @@protoc_insertion_point(module_scope)
