# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AreaPlayInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AreaPlayType_pb2 as AreaPlayType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x41reaPlayInfoNotify.proto\x1a\x12\x41reaPlayType.proto\"Q\n\x12\x41reaPlayInfoNotify\x12\x16\n\x0e\x64\x65tailPlayType\x18\x0c \x01(\r\x12#\n\x0c\x61reaPlayType\x18\t \x01(\x0e\x32\r.AreaPlayTypeB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AreaPlayInfoNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_AREAPLAYINFONOTIFY']._serialized_start=48
  _globals['_AREAPLAYINFONOTIFY']._serialized_end=129
# @@protoc_insertion_point(module_scope)
