# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AskAddFriendRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41skAddFriendRsp.proto\"E\n\x0f\x41skAddFriendRsp\x12\x0f\n\x07retcode\x18\x0f \x01(\x05\x12\r\n\x05param\x18\x01 \x01(\r\x12\x12\n\ntarget_uid\x18\x03 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AskAddFriendRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_ASKADDFRIENDRSP']._serialized_start=25
  _globals['_ASKADDFRIENDRSP']._serialized_end=94
# @@protoc_insertion_point(module_scope)
