# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarSkillMaxChargeCountNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%AvatarSkillMaxChargeCountNotify.proto\"^\n\x1f\x41vatarSkillMaxChargeCountNotify\x12\x0f\n\x07skillId\x18\x03 \x01(\r\x12\x12\n\navatarGuid\x18\x07 \x01(\x04\x12\x16\n\x0emaxChargeCount\x18\x01 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarSkillMaxChargeCountNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_AVATARSKILLMAXCHARGECOUNTNOTIFY']._serialized_start=41
  _globals['_AVATARSKILLMAXCHARGECOUNTNOTIFY']._serialized_end=135
# @@protoc_insertion_point(module_scope)
