# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarTeamUpdateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarTeam_pb2 as AvatarTeam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x41vatarTeamUpdateNotify.proto\x1a\x10\x41vatarTeam.proto\"\xbf\x01\n\x16\x41vatarTeamUpdateNotify\x12\x43\n\x0f\x61vatar_team_map\x18\x04 \x03(\x0b\x32*.AvatarTeamUpdateNotify.AvatarTeamMapEntry\x12\x1d\n\x15temp_avatar_guid_list\x18\r \x03(\x04\x1a\x41\n\x12\x41vatarTeamMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.AvatarTeam:\x02\x38\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarTeamUpdateNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _AVATARTEAMUPDATENOTIFY_AVATARTEAMMAPENTRY._options = None
  _AVATARTEAMUPDATENOTIFY_AVATARTEAMMAPENTRY._serialized_options = b'8\001'
  _globals['_AVATARTEAMUPDATENOTIFY']._serialized_start=51
  _globals['_AVATARTEAMUPDATENOTIFY']._serialized_end=242
  _globals['_AVATARTEAMUPDATENOTIFY_AVATARTEAMMAPENTRY']._serialized_start=177
  _globals['_AVATARTEAMUPDATENOTIFY_AVATARTEAMMAPENTRY']._serialized_end=242
# @@protoc_insertion_point(module_scope)
