# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarFetterDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarFetterInfo_pb2 as AvatarFetterInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x41vatarFetterDataNotify.proto\x1a\x16\x41vatarFetterInfo.proto\"\xa4\x01\n\x16\x41vatarFetterDataNotify\x12\x41\n\rfetterInfoMap\x18\x0b \x03(\x0b\x32*.AvatarFetterDataNotify.FetterInfoMapEntry\x1aG\n\x12\x46\x65tterInfoMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.AvatarFetterInfo:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarFetterDataNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _AVATARFETTERDATANOTIFY_FETTERINFOMAPENTRY._options = None
  _AVATARFETTERDATANOTIFY_FETTERINFOMAPENTRY._serialized_options = b'8\001'
  _globals['_AVATARFETTERDATANOTIFY']._serialized_start=57
  _globals['_AVATARFETTERDATANOTIFY']._serialized_end=221
  _globals['_AVATARFETTERDATANOTIFY_FETTERINFOMAPENTRY']._serialized_start=150
  _globals['_AVATARFETTERDATANOTIFY_FETTERINFOMAPENTRY']._serialized_end=221
# @@protoc_insertion_point(module_scope)
