# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Avatar.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneWeaponInfo_pb2 as SceneWeaponInfo__pb2
import CurVehicleInfo_pb2 as CurVehicleInfo__pb2
import AvatarExcelInfo_pb2 as AvatarExcelInfo__pb2
import SceneReliquaryInfo_pb2 as SceneReliquaryInfo__pb2
import ServerBuff_pb2 as ServerBuff__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Avatar.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\031emu.grasscutter.net.proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x41vatar.proto\x1a\x15SceneWeaponInfo.proto\x1a\x14\x43urVehicleInfo.proto\x1a\x15\x41vatarExcelInfo.proto\x1a\x18SceneReliquaryInfo.proto\x1a\x10ServerBuff.proto\"\xe1\x05\n\x06\x41vatar\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x10\n\x08\x61vatarId\x18\x02 \x01(\r\x12\x0c\n\x04guid\x18\x03 \x01(\x04\x12\x0e\n\x06peerId\x18\x04 \x01(\r\x12\x13\n\x0b\x65quipIdList\x18\x05 \x03(\r\x12\x14\n\x0cskillDepotId\x18\x06 \x01(\r\x12\x14\n\x0ctalentIdList\x18\x07 \x03(\r\x12 \n\x06weapon\x18\x08 \x01(\x0b\x32\x10.SceneWeaponInfo\x12*\n\rreliquaryList\x18\t \x03(\x0b\x32\x13.SceneReliquaryInfo\x12\x1b\n\x13\x63oreProudSkillLevel\x18\x0b \x01(\r\x12\x1e\n\x16inherentProudSkillList\x18\x0c \x03(\r\x12\x31\n\rskillLevelMap\x18\r \x03(\x0b\x32\x1a.Avatar.SkillLevelMapEntry\x12\x45\n\x17proudSkillExtraLevelMap\x18\x0e \x03(\x0b\x32$.Avatar.ProudSkillExtraLevelMapEntry\x12#\n\x0eserverBuffList\x18\x0f \x03(\x0b\x32\x0b.ServerBuff\x12\x19\n\x11teamResonanceList\x18\x10 \x03(\r\x12\x19\n\x11wearingFlycloakId\x18\x11 \x01(\r\x12\x10\n\x08\x62ornTime\x18\x12 \x01(\r\x12\x11\n\tcostumeId\x18\x13 \x01(\r\x12\'\n\x0e\x63urVehicleInfo\x18\x14 \x01(\x0b\x32\x0f.CurVehicleInfo\x12#\n\texcelInfo\x18\x15 \x01(\x0b\x32\x10.AvatarExcelInfo\x12\x10\n\x08\x61nimHash\x18\x16 \x01(\r\x1a\x34\n\x12SkillLevelMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a>\n\x1cProudSkillExtraLevelMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3'
  ,
  dependencies=[SceneWeaponInfo__pb2.DESCRIPTOR,CurVehicleInfo__pb2.DESCRIPTOR,AvatarExcelInfo__pb2.DESCRIPTOR,SceneReliquaryInfo__pb2.DESCRIPTOR,ServerBuff__pb2.DESCRIPTOR,])




_AVATAR_SKILLLEVELMAPENTRY = _descriptor.Descriptor(
  name='SkillLevelMapEntry',
  full_name='Avatar.SkillLevelMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Avatar.SkillLevelMapEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Avatar.SkillLevelMapEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=750,
  serialized_end=802,
)

_AVATAR_PROUDSKILLEXTRALEVELMAPENTRY = _descriptor.Descriptor(
  name='ProudSkillExtraLevelMapEntry',
  full_name='Avatar.ProudSkillExtraLevelMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Avatar.ProudSkillExtraLevelMapEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Avatar.ProudSkillExtraLevelMapEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=804,
  serialized_end=866,
)

_AVATAR = _descriptor.Descriptor(
  name='Avatar',
  full_name='Avatar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Avatar.uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avatarId', full_name='Avatar.avatarId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guid', full_name='Avatar.guid', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peerId', full_name='Avatar.peerId', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='equipIdList', full_name='Avatar.equipIdList', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skillDepotId', full_name='Avatar.skillDepotId', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='talentIdList', full_name='Avatar.talentIdList', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weapon', full_name='Avatar.weapon', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reliquaryList', full_name='Avatar.reliquaryList', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coreProudSkillLevel', full_name='Avatar.coreProudSkillLevel', index=9,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inherentProudSkillList', full_name='Avatar.inherentProudSkillList', index=10,
      number=12, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skillLevelMap', full_name='Avatar.skillLevelMap', index=11,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proudSkillExtraLevelMap', full_name='Avatar.proudSkillExtraLevelMap', index=12,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serverBuffList', full_name='Avatar.serverBuffList', index=13,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='teamResonanceList', full_name='Avatar.teamResonanceList', index=14,
      number=16, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wearingFlycloakId', full_name='Avatar.wearingFlycloakId', index=15,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bornTime', full_name='Avatar.bornTime', index=16,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='costumeId', full_name='Avatar.costumeId', index=17,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='curVehicleInfo', full_name='Avatar.curVehicleInfo', index=18,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='excelInfo', full_name='Avatar.excelInfo', index=19,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='animHash', full_name='Avatar.animHash', index=20,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_AVATAR_SKILLLEVELMAPENTRY, _AVATAR_PROUDSKILLEXTRALEVELMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=866,
)

_AVATAR_SKILLLEVELMAPENTRY.containing_type = _AVATAR
_AVATAR_PROUDSKILLEXTRALEVELMAPENTRY.containing_type = _AVATAR
_AVATAR.fields_by_name['weapon'].message_type = SceneWeaponInfo__pb2._SCENEWEAPONINFO
_AVATAR.fields_by_name['reliquaryList'].message_type = SceneReliquaryInfo__pb2._SCENERELIQUARYINFO
_AVATAR.fields_by_name['skillLevelMap'].message_type = _AVATAR_SKILLLEVELMAPENTRY
_AVATAR.fields_by_name['proudSkillExtraLevelMap'].message_type = _AVATAR_PROUDSKILLEXTRALEVELMAPENTRY
_AVATAR.fields_by_name['serverBuffList'].message_type = ServerBuff__pb2._SERVERBUFF
_AVATAR.fields_by_name['curVehicleInfo'].message_type = CurVehicleInfo__pb2._CURVEHICLEINFO
_AVATAR.fields_by_name['excelInfo'].message_type = AvatarExcelInfo__pb2._AVATAREXCELINFO
DESCRIPTOR.message_types_by_name['Avatar'] = _AVATAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Avatar = _reflection.GeneratedProtocolMessageType('Avatar', (_message.Message,), {

  'SkillLevelMapEntry' : _reflection.GeneratedProtocolMessageType('SkillLevelMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _AVATAR_SKILLLEVELMAPENTRY,
    '__module__' : 'Avatar_pb2'
    # @@protoc_insertion_point(class_scope:Avatar.SkillLevelMapEntry)
    })
  ,

  'ProudSkillExtraLevelMapEntry' : _reflection.GeneratedProtocolMessageType('ProudSkillExtraLevelMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _AVATAR_PROUDSKILLEXTRALEVELMAPENTRY,
    '__module__' : 'Avatar_pb2'
    # @@protoc_insertion_point(class_scope:Avatar.ProudSkillExtraLevelMapEntry)
    })
  ,
  'DESCRIPTOR' : _AVATAR,
  '__module__' : 'Avatar_pb2'
  # @@protoc_insertion_point(class_scope:Avatar)
  })
_sym_db.RegisterMessage(Avatar)
_sym_db.RegisterMessage(Avatar.SkillLevelMapEntry)
_sym_db.RegisterMessage(Avatar.ProudSkillExtraLevelMapEntry)


DESCRIPTOR._options = None
_AVATAR_SKILLLEVELMAPENTRY._options = None
_AVATAR_PROUDSKILLEXTRALEVELMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
