# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BargainSnapshot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x42\x61rgainSnapshot.proto\"o\n\x0f\x42\x61rgainSnapshot\x12\x1b\n\x13Unk3300_MHFDEBOBFNE\x18\n \x01(\r\x12\x11\n\tbargainId\x18\x07 \x01(\r\x12\x0f\n\x07\x63urMood\x18\r \x01(\x05\x12\x1b\n\x13Unk3300_KOCJELACJLM\x18\x06 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BargainSnapshot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_BARGAINSNAPSHOT']._serialized_start=25
  _globals['_BARGAINSNAPSHOT']._serialized_end=136
# @@protoc_insertion_point(module_scope)
