# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BartenderCompleteOrderReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x42\x61rtenderCompleteOrderReq.proto\x1a\x0fItemParam.proto\"\xc1\x01\n\x19\x42\x61rtenderCompleteOrderReq\x12\x1b\n\x13optional_order_list\x18\x08 \x03(\r\x12\x13\n\x0bLGPFMKPDGEO\x18\x04 \x01(\r\x12\x17\n\x0fis_view_formula\x18\t \x01(\x08\x12\x10\n\x08quest_id\x18\n \x01(\r\x12\x1d\n\titem_list\x18\r \x03(\x0b\x32\n.ItemParam\x12\x13\n\x0b\x45\x41IDPIBKEOH\x18\x06 \x01(\r\x12\x13\n\x0b\x44KLPLLBEHGI\x18\x02 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BartenderCompleteOrderReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_BARTENDERCOMPLETEORDERREQ']._serialized_start=53
  _globals['_BARTENDERCOMPLETEORDERREQ']._serialized_end=246
# @@protoc_insertion_point(module_scope)
