# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BlessingActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n BlessingActivityDetailInfo.proto\"\xb6\x02\n\x1a\x42lessingActivityDetailInfo\x12\x19\n\x11is_content_closed\x18\n \x01(\x08\x12\x14\n\x0cis_activated\x18\x04 \x01(\x08\x12\x13\n\x0b\x44\x43KODCGGHDJ\x18\x02 \x01(\r\x12\x1a\n\x12\x63ontent_close_time\x18\x05 \x01(\r\x12\x13\n\x0bGNNKHIMAANK\x18\x08 \x01(\r\x12\x19\n\x11next_refresh_time\x18\x0e \x01(\r\x12?\n\x0bpic_num_map\x18\x0c \x03(\x0b\x32*.BlessingActivityDetailInfo.PicNumMapEntry\x12\x13\n\x0b\x45HJJNMKIPEF\x18\x06 \x01(\r\x1a\x30\n\x0ePicNumMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BlessingActivityDetailInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _BLESSINGACTIVITYDETAILINFO_PICNUMMAPENTRY._options = None
  _BLESSINGACTIVITYDETAILINFO_PICNUMMAPENTRY._serialized_options = b'8\001'
  _globals['_BLESSINGACTIVITYDETAILINFO']._serialized_start=37
  _globals['_BLESSINGACTIVITYDETAILINFO']._serialized_end=347
  _globals['_BLESSINGACTIVITYDETAILINFO_PICNUMMAPENTRY']._serialized_start=299
  _globals['_BLESSINGACTIVITYDETAILINFO_PICNUMMAPENTRY']._serialized_end=347
# @@protoc_insertion_point(module_scope)
