# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BlessingAcceptGivePicRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x42lessingAcceptGivePicRsp.proto\"V\n\x18\x42lessingAcceptGivePicRsp\x12\r\n\x05picId\x18\x0c \x01(\r\x12\r\n\x05index\x18\r \x01(\r\x12\x0b\n\x03uid\x18\x0b \x01(\r\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BlessingAcceptGivePicRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_BLESSINGACCEPTGIVEPICRSP']._serialized_start=34
  _globals['_BLESSINGACCEPTGIVEPICRSP']._serialized_end=120
# @@protoc_insertion_point(module_scope)
