# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BlossomBriefInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BlossomBriefInfo_pb2 as BlossomBriefInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x42lossomBriefInfoNotify.proto\x1a\x16\x42lossomBriefInfo.proto\"B\n\x16\x42lossomBriefInfoNotify\x12(\n\rbriefInfoList\x18\t \x03(\x0b\x32\x11.BlossomBriefInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BlossomBriefInfoNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_BLOSSOMBRIEFINFONOTIFY']._serialized_start=56
  _globals['_BLOSSOMBRIEFINFONOTIFY']._serialized_end=122
# @@protoc_insertion_point(module_scope)
