# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BlossomScheduleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x42lossomScheduleInfo.proto\"\x86\x01\n\x13\x42lossomScheduleInfo\x12\x11\n\trefreshId\x18\x06 \x01(\r\x12\r\n\x05state\x18\t \x01(\r\x12\x14\n\x0c\x63ircleCampId\x18\x01 \x01(\r\x12\x16\n\x0e\x66inishProgress\x18\x0c \x01(\r\x12\r\n\x05round\x18\x0e \x01(\r\x12\x10\n\x08progress\x18\x0f \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BlossomScheduleInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_BLOSSOMSCHEDULEINFO']._serialized_start=30
  _globals['_BLOSSOMSCHEDULEINFO']._serialized_end=164
# @@protoc_insertion_point(module_scope)
