# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BOEHIBPDLNM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x42OEHIBPDLNM.proto\x1a\x0cVector.proto\"\xcb\x01\n\x0b\x42OEHIBPDLNM\x12\x11\n\tentity_id\x18\x06 \x01(\r\x12\x13\n\x0bKNFNGDLJPEO\x18\x01 \x01(\x08\x12\x13\n\x0bMENJDNJINOA\x18\x02 \x01(\t\x12\x13\n\x0bMOFFKMLAHDC\x18\x05 \x01(\x08\x12\r\n\x05speed\x18\x07 \x01(\x02\x12\x13\n\x0b\x43ILNDIOBPLP\x18\t \x01(\x02\x12\x13\n\x0bKLALFMECMLM\x18\x0f \x03(\r\x12\x1c\n\x0bHOHCJADGKFD\x18\x0c \x01(\x0b\x32\x07.Vector\x12\x13\n\x0b\x43HMKAEIELMG\x18\x0b \x01(\x02\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BOEHIBPDLNM_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_BOEHIBPDLNM']._serialized_start=36
  _globals['_BOEHIBPDLNM']._serialized_end=239
# @@protoc_insertion_point(module_scope)
