# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BOIPHJCFLBK.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import NFHBHHJAJDA_pb2 as NFHBHHJAJDA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x42OIPHJCFLBK.proto\x1a\x11NFHBHHJAJDA.proto\"\xea\x02\n\x0b\x42OIPHJCFLBK\x12\x13\n\x0bimpfndpedoa\x18\x0b \x01(\x02\x12\x16\n\x0e\x61ttackTargetId\x18\x0f \x01(\r\x12\x13\n\x0bgjnmmadghcn\x18\x06 \x01(\x02\x12!\n\x0bhdbonehdhll\x18\x01 \x03(\x0b\x32\x0c.NFHBHHJAJDA\x12\x13\n\x0b\x64laddidhjbc\x18\x03 \x01(\x02\x12\x13\n\x0bogigbahpfog\x18\x0e \x01(\x02\x12\x32\n\x0b\x64lhfjjbaggg\x18\x0c \x03(\x0b\x32\x1d.BOIPHJCFLBK.DlhfjjbagggEntry\x12\x13\n\x0bnnlkpdinema\x18\x07 \x01(\r\x12\x13\n\x0bkldlcmkpnaa\x18\x04 \x01(\r\x12\x13\n\x0b\x61kgfenlfekh\x18\t \x01(\r\x12\x13\n\x0b\x65gfkffbealf\x18\x05 \x01(\r\x12\x10\n\x08\x65ntityId\x18\x02 \x01(\r\x1a\x32\n\x10\x44lhfjjbagggEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BOIPHJCFLBK_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _BOIPHJCFLBK_DLHFJJBAGGGENTRY._options = None
  _BOIPHJCFLBK_DLHFJJBAGGGENTRY._serialized_options = b'8\001'
  _globals['_BOIPHJCFLBK']._serialized_start=41
  _globals['_BOIPHJCFLBK']._serialized_end=403
  _globals['_BOIPHJCFLBK_DLHFJJBAGGGENTRY']._serialized_start=353
  _globals['_BOIPHJCFLBK_DLHFJJBAGGGENTRY']._serialized_end=403
# @@protoc_insertion_point(module_scope)
