# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BreakoutAction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BreakoutActionType_pb2 as BreakoutActionType__pb2
import BreakoutVector2_pb2 as BreakoutVector2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42reakoutAction.proto\x1a\x18\x42reakoutActionType.proto\x1a\x15\x42reakoutVector2.proto\"\xc2\x03\n\x0e\x42reakoutAction\x12\'\n\nactionType\x18\x01 \x01(\x0e\x32\x13.BreakoutActionType\x12\x16\n\x0e\x63lientGameTime\x18\x02 \x01(\x04\x12\x16\n\x0eserverGameTime\x18\x03 \x01(\x04\x12\x13\n\x0bmbfjjacbmck\x18\x04 \x01(\x08\x12\x13\n\x0bgddolpoemjk\x18\x05 \x01(\r\x12\x13\n\x0bjoandihiadc\x18\x06 \x01(\r\x12\x1d\n\x03pos\x18\x07 \x01(\x0b\x32\x10.BreakoutVector2\x12%\n\x0bmjehpphliia\x18\x08 \x01(\x0b\x32\x10.BreakoutVector2\x12\r\n\x05speed\x18\t \x01(\x05\x12\x0e\n\x06peerId\x18\n \x01(\r\x12\x13\n\x0b\x65lementType\x18\x0b \x01(\r\x12\x13\n\x0binhflokdoal\x18\x0c \x01(\r\x12\x13\n\x0b\x61piembahlab\x18\r \x01(\r\x12\x13\n\x0bmhkdmdjeaan\x18\x0e \x01(\x08\x12%\n\x0b\x63jegmomlbck\x18\x0f \x01(\x0b\x32\x10.BreakoutVector2\x12\x13\n\x0bidngdpalicj\x18\x10 \x01(\r\x12\x0e\n\x06offset\x18\x11 \x01(\x05\x12\x13\n\x0blccmdkibdpf\x18\x12 \x01(\x04\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BreakoutAction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_BREAKOUTACTION']._serialized_start=74
  _globals['_BREAKOUTACTION']._serialized_end=524
# @@protoc_insertion_point(module_scope)
