# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BrickBreakerPlayerBattleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"BrickBreakerPlayerBattleInfo.proto\"\x9a\x01\n\x1c\x42rickBreakerPlayerBattleInfo\x12\x11\n\tskillList\x18\t \x03(\r\x12\x0f\n\x07isReady\x18\x06 \x01(\x08\x12\x10\n\x08nickname\x18\x0f \x01(\t\x12\x12\n\nisChanging\x18\x0e \x01(\x08\x12\x11\n\tcostumeId\x18\x0c \x03(\r\x12\x10\n\x08\x61vatarId\x18\x05 \x03(\r\x12\x0b\n\x03uid\x18\x03 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BrickBreakerPlayerBattleInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_BRICKBREAKERPLAYERBATTLEINFO']._serialized_start=39
  _globals['_BRICKBREAKERPLAYERBATTLEINFO']._serialized_end=193
# @@protoc_insertion_point(module_scope)
