# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannellerSlabTakeoffBuffReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ChannellerSlabTakeoffBuffReq.proto\"S\n\x1c\x43hannellerSlabTakeoffBuffReq\x12\x13\n\x0b\x66hableimdgl\x18\x08 \x01(\x08\x12\x0e\n\x06\x62uffId\x18\n \x01(\r\x12\x0e\n\x06slotId\x18\r \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannellerSlabTakeoffBuffReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_CHANNELLERSLABTAKEOFFBUFFREQ']._serialized_start=38
  _globals['_CHANNELLERSLABTAKEOFFBUFFREQ']._serialized_end=121
# @@protoc_insertion_point(module_scope)
