# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannellerSlabLoopDungeonSelectConditionReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1ChannellerSlabLoopDungeonSelectConditionReq.proto\"v\n+ChannellerSlabLoopDungeonSelectConditionReq\x12\x15\n\rdifficulty_id\x18\x0b \x01(\r\x12\x19\n\x11\x63ondition_id_list\x18\x0f \x03(\r\x12\x15\n\rdungeon_index\x18\x06 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannellerSlabLoopDungeonSelectConditionReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_CHANNELLERSLABLOOPDUNGEONSELECTCONDITIONREQ']._serialized_start=53
  _globals['_CHANNELLERSLABLOOPDUNGEONSELECTCONDITIONREQ']._serialized_end=171
# @@protoc_insertion_point(module_scope)
