# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannellerSlabEnterLoopDungeonReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ChannellerSlabEnterLoopDungeonReq.proto\"y\n!ChannellerSlabEnterLoopDungeonReq\x12\x14\n\x0c\x64ifficultyId\x18\x0e \x01(\r\x12\x14\n\x0c\x64ungeonIndex\x18\n \x01(\r\x12\x0f\n\x07pointId\x18\x03 \x01(\r\x12\x17\n\x0f\x63onditionIdList\x18\x02 \x03(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannellerSlabEnterLoopDungeonReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_CHANNELLERSLABENTERLOOPDUNGEONREQ']._serialized_start=43
  _globals['_CHANNELLERSLABENTERLOOPDUNGEONREQ']._serialized_end=164
# @@protoc_insertion_point(module_scope)
