# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CheckSegmentCRCReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SegmentCRCInfo_pb2 as SegmentCRCInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43heckSegmentCRCReq.proto\x1a\x14SegmentCRCInfo.proto\"8\n\x12\x43heckSegmentCRCReq\x12\"\n\tinfo_list\x18\x0c \x03(\x0b\x32\x0f.SegmentCRCInfoB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CheckSegmentCRCReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_CHECKSEGMENTCRCREQ']._serialized_start=50
  _globals['_CHECKSEGMENTCRCREQ']._serialized_end=106
# @@protoc_insertion_point(module_scope)
