# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CityReputationInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CFHIGHGJCBF_pb2 as CFHIGHGJCBF__pb2
import CityReputationExploreInfo_pb2 as CityReputationExploreInfo__pb2
import LAELNKCMNMP_pb2 as LAELNKCMNMP__pb2
import NMIPDNNMELF_pb2 as NMIPDNNMELF__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43ityReputationInfo.proto\x1a\x11\x43\x46HIGHGJCBF.proto\x1a\x1f\x43ityReputationExploreInfo.proto\x1a\x11LAELNKCMNMP.proto\x1a\x11NMIPDNNMELF.proto\"\xa9\x02\n\x12\x43ityReputationInfo\x12!\n\x0bMFGPICPIMLA\x18\x02 \x01(\x0b\x32\x0c.LAELNKCMNMP\x12\x30\n\x0c\x65xplore_info\x18\x04 \x01(\x0b\x32\x1a.CityReputationExploreInfo\x12!\n\x0bONPMKPDMNHC\x18\n \x01(\x0b\x32\x0c.CFHIGHGJCBF\x12 \n\x18total_accept_request_num\x18\x0f \x01(\r\x12\x1f\n\x17taken_level_reward_list\x18\x06 \x03(\r\x12!\n\x0b\x43MHDHFKAMAL\x18\x07 \x01(\x0b\x32\x0c.NMIPDNNMELF\x12\x0b\n\x03\x65xp\x18\x05 \x01(\r\x12\r\n\x05level\x18\x0e \x01(\r\x12\x19\n\x11next_refresh_time\x18\x0c \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CityReputationInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_CITYREPUTATIONINFO']._serialized_start=119
  _globals['_CITYREPUTATIONINFO']._serialized_end=416
# @@protoc_insertion_point(module_scope)
