# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CJKNEMMPMGN.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DDJMHLCDPHO_pb2 as DDJMHLCDPHO__pb2
import DOCPAPKDBBK_pb2 as DOCPAPKDBBK__pb2
import KIMICJIEGDD_pb2 as KIMICJIEGDD__pb2
import NHIJPCNBKJE_pb2 as NHIJPCNBKJE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43JKNEMMPMGN.proto\x1a\x11\x44\x44JMHLCDPHO.proto\x1a\x11\x44OCPAPKDBBK.proto\x1a\x11KIMICJIEGDD.proto\x1a\x11NHIJPCNBKJE.proto\"\xbc\x01\n\x0b\x43JKNEMMPMGN\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x0bIMBHJIKNEOC\x18\x02 \x03(\x0b\x32\x0c.DDJMHLCDPHO\x12\x13\n\x0b\x44NJPIOJIFIE\x18\x03 \x03(\t\x12!\n\x0bPNFIHGPGNKD\x18\x04 \x03(\x0b\x32\x0c.NHIJPCNBKJE\x12!\n\x0bKOHHOLKLCNH\x18\x05 \x01(\x0b\x32\x0c.DOCPAPKDBBK\x12!\n\x0b\x46\x46\x44\x41HCPMGAI\x18\x06 \x01(\x0e\x32\x0c.KIMICJIEGDDB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CJKNEMMPMGN_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_CJKNEMMPMGN']._serialized_start=98
  _globals['_CJKNEMMPMGN']._serialized_end=286
# @@protoc_insertion_point(module_scope)
