# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CoinCollectInterruptPlayRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!CoinCollectInterruptPlayRsp.proto\"A\n\x1b\x43oinCollectInterruptPlayRsp\x12\x11\n\tgalleryId\x18\x07 \x01(\r\x12\x0f\n\x07retcode\x18\x06 \x01(\x05\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CoinCollectInterruptPlayRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_COINCOLLECTINTERRUPTPLAYRSP']._serialized_start=37
  _globals['_COINCOLLECTINTERRUPTPLAYRSP']._serialized_end=102
# @@protoc_insertion_point(module_scope)
