# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CoinCollectPrepareStageNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CoinCollectInfo_pb2 as CoinCollectInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#CoinCollectPrepareStageNotify.proto\x1a\x15\x43oinCollectInfo.proto\"F\n\x1d\x43oinCollectPrepareStageNotify\x12%\n\x0blocpgggjmdl\x18\x07 \x01(\x0b\x32\x10.CoinCollectInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CoinCollectPrepareStageNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_COINCOLLECTPREPARESTAGENOTIFY']._serialized_start=62
  _globals['_COINCOLLECTPREPARESTAGENOTIFY']._serialized_end=132
# @@protoc_insertion_point(module_scope)
