# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CoinCollectLevelData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CoinCollectTeamInfoData_pb2 as CoinCollectTeamInfoData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43oinCollectLevelData.proto\x1a\x1d\x43oinCollectTeamInfoData.proto\"\xc2\x02\n\x14\x43oinCollectLevelData\x12\x13\n\x0bmffbbcobifb\x18\x0f \x01(\x08\x12-\n\x0bmdjfnblbncn\x18\x06 \x03(\x0b\x32\x18.CoinCollectTeamInfoData\x12-\n\x0bjkglemblhjj\x18\x05 \x01(\x0b\x32\x18.CoinCollectTeamInfoData\x12\x13\n\x0b\x64mgfjomildi\x18\r \x01(\r\x12\x13\n\x0boahobildeen\x18\t \x01(\x08\x12\x13\n\x0bocbgniehaae\x18\x02 \x01(\x08\x12\x13\n\x0bmipkplghgdb\x18\n \x01(\r\x12\x13\n\x0bgcgfggieage\x18\x08 \x01(\r\x12\x13\n\x0boepemecbhfp\x18\x0e \x01(\r\x12\x13\n\x0b\x66\x63\x65\x64mbblknb\x18\x03 \x01(\r\x12\x0f\n\x07levelId\x18\x07 \x01(\r\x12\x13\n\x0b\x63\x61\x65pnfpolia\x18\x0c \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CoinCollectLevelData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_COINCOLLECTLEVELDATA']._serialized_start=62
  _globals['_COINCOLLECTLEVELDATA']._serialized_end=384
# @@protoc_insertion_point(module_scope)
