# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CrystalLinkEnterDungeonReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CrystalLinkTeamInfo_pb2 as CrystalLinkTeamInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n CrystalLinkEnterDungeonReq.proto\x1a\x19\x43rystalLinkTeamInfo.proto\"o\n\x1a\x43rystalLinkEnterDungeonReq\x12*\n\x0cteamInfoList\x18\x07 \x03(\x0b\x32\x14.CrystalLinkTeamInfo\x12\x0f\n\x07levelId\x18\x08 \x01(\r\x12\x14\n\x0c\x64ifficultyId\x18\x04 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CrystalLinkEnterDungeonReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_CRYSTALLINKENTERDUNGEONREQ']._serialized_start=63
  _globals['_CRYSTALLINKENTERDUNGEONREQ']._serialized_end=174
# @@protoc_insertion_point(module_scope)
