# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CrystalLinkActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CrystalLinkLevelInfo_pb2 as CrystalLinkLevelInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#CrystalLinkActivityDetailInfo.proto\x1a\x1a\x43rystalLinkLevelInfo.proto\"f\n\x1d\x43rystalLinkActivityDetailInfo\x12.\n\x0flevel_info_list\x18\x05 \x03(\x0b\x32\x15.CrystalLinkLevelInfo\x12\x15\n\rdifficulty_id\x18\x0b \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CrystalLinkActivityDetailInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_CRYSTALLINKACTIVITYDETAILINFO']._serialized_start=67
  _globals['_CRYSTALLINKACTIVITYDETAILINFO']._serialized_end=169
# @@protoc_insertion_point(module_scope)
