# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CrystalLinkEnterDungeonRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CrystalLinkTeamInfo_pb2 as CrystalLinkTeamInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n CrystalLinkEnterDungeonRsp.proto\x1a\x19\x43rystalLinkTeamInfo.proto\"\x84\x01\n\x1a\x43rystalLinkEnterDungeonRsp\x12\x0f\n\x07retcode\x18\t \x01(\x05\x12\x15\n\rdifficulty_id\x18\x01 \x01(\r\x12,\n\x0eteam_info_list\x18\x0c \x03(\x0b\x32\x14.CrystalLinkTeamInfo\x12\x10\n\x08level_id\x18\x05 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CrystalLinkEnterDungeonRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_CRYSTALLINKENTERDUNGEONRSP']._serialized_start=64
  _globals['_CRYSTALLINKENTERDUNGEONRSP']._serialized_end=196
# @@protoc_insertion_point(module_scope)
