# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomDungeonResultInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChallengeBrief_pb2 as ChallengeBrief__pb2
import CustomDungeonFinishType_pb2 as CustomDungeonFinishType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x43ustomDungeonResultInfo.proto\x1a\x14\x43hallengeBrief.proto\x1a\x1d\x43ustomDungeonFinishType.proto\"\xfa\x01\n\x17\x43ustomDungeonResultInfo\x12\x13\n\x0b\x45\x42\x44MFAMBJNG\x18\t \x01(\x08\x12-\n\x0b\x66inish_type\x18\x01 \x01(\x0e\x32\x18.CustomDungeonFinishType\x12\x14\n\x0cgot_coin_num\x18\x02 \x01(\r\x12\x18\n\x10is_arrive_finish\x18\x0c \x01(\x08\x12\x13\n\x0bJNDPMPEBPIK\x18\x08 \x01(\x08\x12\x11\n\ttime_cost\x18\r \x01(\r\x12\x14\n\x0c\x64ungeon_guid\x18\x0e \x01(\x04\x12-\n\x14\x63hild_challenge_list\x18\x0f \x03(\x0b\x32\x0f.ChallengeBriefB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CustomDungeonResultInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_CUSTOMDUNGEONRESULTINFO']._serialized_start=87
  _globals['_CUSTOMDUNGEONRESULTINFO']._serialized_end=337
# @@protoc_insertion_point(module_scope)
