# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomDungeon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CustomDungeonSetting_pb2 as CustomDungeonSetting__pb2
import CustomDungeonRoom_pb2 as CustomDungeonRoom__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43ustomDungeon.proto\x1a\x1a\x43ustomDungeonSetting.proto\x1a\x17\x43ustomDungeonRoom.proto\"\x85\x01\n\rCustomDungeon\x12\x13\n\x0b\x64ungeonGuid\x18\x08 \x01(\x04\x12$\n\x08roomList\x18\x03 \x03(\x0b\x32\x12.CustomDungeonRoom\x12&\n\x07setting\x18\x01 \x01(\x0b\x32\x15.CustomDungeonSetting\x12\x11\n\tdungeonId\x18\x04 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CustomDungeon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_CUSTOMDUNGEON']._serialized_start=77
  _globals['_CUSTOMDUNGEON']._serialized_end=210
# @@protoc_insertion_point(module_scope)
