# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DCAJABFLBPO.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UgcType_pb2 as UgcType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x44\x43\x41JABFLBPO.proto\x1a\rUgcType.proto\";\n\x0b\x44\x43\x41JABFLBPO\x12\x1a\n\x08ugc_type\x18\x0f \x01(\x0e\x32\x08.UgcType\x12\x10\n\x08ugc_guid\x18\x07 \x01(\x04\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DCAJABFLBPO_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_DCAJABFLBPO']._serialized_start=36
  _globals['_DCAJABFLBPO']._serialized_end=95
# @@protoc_insertion_point(module_scope)
