# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DiceReroll.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGDiceSideType_pb2 as GCGDiceSideType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x44iceReroll.proto\x1a\x15GCGDiceSideType.proto\"g\n\nDiceReroll\x12\x14\n\x0c\x63ontrollerId\x18\x08 \x01(\r\x12&\n\x0c\x64iceSideList\x18\x07 \x03(\x0e\x32\x10.GCGDiceSideType\x12\x1b\n\x13selectDiceIndexList\x18\r \x03(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DiceReroll_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_DICEREROLL']._serialized_start=43
  _globals['_DICEREROLL']._serialized_end=146
# @@protoc_insertion_point(module_scope)
