# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DKPDHJGFLKM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BreakoutSnapShot_pb2 as BreakoutSnapShot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x44KPDHJGFLKM.proto\x1a\x16\x42reakoutSnapShot.proto\"5\n\x0b\x44KPDHJGFLKM\x12&\n\x0b\x45NNAPNPNDNB\x18\x04 \x01(\x0b\x32\x11.BreakoutSnapShotB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DKPDHJGFLKM_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_DKPDHJGFLKM']._serialized_start=45
  _globals['_DKPDHJGFLKM']._serialized_end=98
# @@protoc_insertion_point(module_scope)
