# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DOINBFHLBHP.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x44OINBFHLBHP.proto*\xcc\x02\n\x0b\x44OINBFHLBHP\x12\x1b\n\x17\x44OINBFHLBHP_EIPEABACFBI\x10\x00\x12\x1b\n\x17\x44OINBFHLBHP_MACECMMLGAN\x10\x01\x12\x1b\n\x17\x44OINBFHLBHP_POOOGFDEDPD\x10\x02\x12\x1b\n\x17\x44OINBFHLBHP_DKGELPINPBA\x10\x03\x12\x1b\n\x17\x44OINBFHLBHP_NPPJKPANJFM\x10\x04\x12\x1b\n\x17\x44OINBFHLBHP_CPDLHPLGNAH\x10\x05\x12\x1b\n\x17\x44OINBFHLBHP_OPFGEJBFJAI\x10\x06\x12\x1b\n\x17\x44OINBFHLBHP_EKGOCLLJJKB\x10\x07\x12\x1b\n\x17\x44OINBFHLBHP_BGBLGFCDLEG\x10\x08\x12\x1b\n\x17\x44OINBFHLBHP_GGCLFNPFOJI\x10\t\x12\x1b\n\x17\x44OINBFHLBHP_ENIBHBFJNIK\x10\nB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DOINBFHLBHP_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_DOINBFHLBHP']._serialized_start=22
  _globals['_DOINBFHLBHP']._serialized_end=354
# @@protoc_insertion_point(module_scope)
