# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DoRoguelikeDungeonCardGachaReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$DoRoguelikeDungeonCardGachaReq.proto\"C\n\x1e\x44oRoguelikeDungeonCardGachaReq\x12\x0e\n\x06\x63\x65llId\x18\r \x01(\r\x12\x11\n\tdungeonId\x18\x06 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DoRoguelikeDungeonCardGachaReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_DOROGUELIKEDUNGEONCARDGACHAREQ']._serialized_start=40
  _globals['_DOROGUELIKEDUNGEONCARDGACHAREQ']._serialized_end=107
# @@protoc_insertion_point(module_scope)
