# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DraftGuestReplyTwiceConfirmRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$DraftGuestReplyTwiceConfirmRsp.proto\"S\n\x1e\x44raftGuestReplyTwiceConfirmRsp\x12\x0f\n\x07retcode\x18\x03 \x01(\x05\x12\x0f\n\x07isAgree\x18\x05 \x01(\x08\x12\x0f\n\x07\x64raftId\x18\x0f \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DraftGuestReplyTwiceConfirmRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_DRAFTGUESTREPLYTWICECONFIRMRSP']._serialized_start=40
  _globals['_DRAFTGUESTREPLYTWICECONFIRMRSP']._serialized_end=123
# @@protoc_insertion_point(module_scope)
