# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DragonSpineActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DragonSpineChapterInfo_pb2 as DragonSpineChapterInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#DragonSpineActivityDetailInfo.proto\x1a\x1c\x44ragonSpineChapterInfo.proto\"\xe0\x01\n\x1d\x44ragonSpineActivityDetailInfo\x12\x13\n\x0bNIPPAPELMPN\x18\x07 \x01(\r\x12\x13\n\x0bPOIDNDIECFP\x18\x01 \x01(\r\x12\x13\n\x0bPBPIPINOBLB\x18\x0b \x01(\r\x12\x1c\n\x14weapon_enhance_level\x18\x0e \x01(\r\x12\x13\n\x0bPEJFBHBOLEA\x18\r \x01(\r\x12\x32\n\x11\x63hapter_info_list\x18\x08 \x03(\x0b\x32\x17.DragonSpineChapterInfo\x12\x19\n\x11is_content_closed\x18\x0f \x01(\x08\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DragonSpineActivityDetailInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_DRAGONSPINEACTIVITYDETAILINFO']._serialized_start=70
  _globals['_DRAGONSPINEACTIVITYDETAILINFO']._serialized_end=294
# @@protoc_insertion_point(module_scope)
