# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DragonSpineChapterFinishNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$DragonSpineChapterFinishNotify.proto\"c\n\x1e\x44ragonSpineChapterFinishNotify\x12\x12\n\nscheduleId\x18\x05 \x01(\r\x12\x1a\n\x12weaponEnhanceLevel\x18\x02 \x01(\r\x12\x11\n\tchapterId\x18\t \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DragonSpineChapterFinishNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_DRAGONSPINECHAPTERFINISHNOTIFY']._serialized_start=40
  _globals['_DRAGONSPINECHAPTERFINISHNOTIFY']._serialized_end=139
# @@protoc_insertion_point(module_scope)
