# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Duel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGCostReviseInfo_pb2 as GCGCostReviseInfo__pb2
import GCGGameBusinessType_pb2 as GCGGameBusinessType__pb2
import GCGPhase_pb2 as GCGPhase__pb2
import GCGCard_pb2 as GCGCard__pb2
import GCGMessagePack_pb2 as GCGMessagePack__pb2
import GCGControllerShowInfo_pb2 as GCGControllerShowInfo__pb2
import Unk3300_ADHENCIFKNI_pb2 as Unk3300__ADHENCIFKNI__pb2
import GCGPVEIntention_pb2 as GCGPVEIntention__pb2
import GCGPlayerField_pb2 as GCGPlayerField__pb2
import GCGDuelChallenge_pb2 as GCGDuelChallenge__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nDuel.proto\x1a\x17GCGCostReviseInfo.proto\x1a\x19GCGGameBusinessType.proto\x1a\x0eGCGPhase.proto\x1a\rGCGCard.proto\x1a\x14GCGMessagePack.proto\x1a\x1bGCGControllerShowInfo.proto\x1a\x19Unk3300_ADHENCIFKNI.proto\x1a\x15GCGPVEIntention.proto\x1a\x14GCGPlayerField.proto\x1a\x16GCGDuelChallenge.proto\"\x92\x05\n\x04\x44uel\x12\x1a\n\x08\x63\x61rdList\x18\x01 \x03(\x0b\x32\x08.GCGCard\x12\x1b\n\x13Unk3300_JHDDNKFPINA\x18\x05 \x01(\r\x12\"\n\x19\x66orbidFinishChallengeList\x18\xc1\x0f \x03(\r\x12\"\n\x0fhistoryCardList\x18\xae\n \x03(\x0b\x32\x08.GCGCard\x12,\n\x12historyMsgPackList\x18\xe4\x0c \x03(\x0b\x32\x0f.GCGMessagePack\x12\x1b\n\x13Unk3300_BIANMOPDEHO\x18\x0e \x01(\r\x12,\n\x0cshowInfoList\x18\n \x03(\x0b\x32\x16.GCGControllerShowInfo\x12\x32\n\x13Unk3300_CDCMBOKBLAK\x18\x9e\x0f \x03(\x0b\x32\x14.Unk3300_ADHENCIFKNI\x12\'\n\rintentionList\x18\x0f \x03(\x0b\x32\x10.GCGPVEIntention\x12&\n\ncostRevise\x18\x06 \x01(\x0b\x32\x12.GCGCostReviseInfo\x12\x14\n\x0c\x63ontrollerId\x18\x02 \x01(\r\x12\"\n\tfieldList\x18\x03 \x03(\x0b\x32\x0f.GCGPlayerField\x12*\n\x0c\x62usinessType\x18\x07 \x01(\x0e\x32\x14.GCGGameBusinessType\x12\x18\n\x05phase\x18\x08 \x01(\x0b\x32\t.GCGPhase\x12(\n\rchallengeList\x18% \x03(\x0b\x32\x11.GCGDuelChallenge\x12\x12\n\ncardIdList\x18\x0c \x03(\r\x12\x11\n\tserverSeq\x18\x0b \x01(\r\x12\r\n\x05round\x18\x04 \x01(\r\x12\x0e\n\x06gameId\x18\t \x01(\r\x12\x1b\n\x13Unk3300_JBBMBKGOONO\x18\r \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Duel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_DUEL']._serialized_start=245
  _globals['_DUEL']._serialized_end=903
# @@protoc_insertion_point(module_scope)
