# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DungeonCandidateTeamPlayerLeaveNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DungeonCandidateTeamPlayerLeaveReason_pb2 as DungeonCandidateTeamPlayerLeaveReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+DungeonCandidateTeamPlayerLeaveNotify.proto\x1a+DungeonCandidateTeamPlayerLeaveReason.proto\"r\n%DungeonCandidateTeamPlayerLeaveNotify\x12\x36\n\x06reason\x18\x02 \x01(\x0e\x32&.DungeonCandidateTeamPlayerLeaveReason\x12\x11\n\tplayerUid\x18\x0c \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DungeonCandidateTeamPlayerLeaveNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_DUNGEONCANDIDATETEAMPLAYERLEAVENOTIFY']._serialized_start=92
  _globals['_DUNGEONCANDIDATETEAMPLAYERLEAVENOTIFY']._serialized_end=206
# @@protoc_insertion_point(module_scope)
