# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DynamicLayerNodes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DynamicSVONode_pb2 as DynamicSVONode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x44ynamicLayerNodes.proto\x1a\x14\x44ynamicSVONode.proto\"B\n\x11\x44ynamicLayerNodes\x12\r\n\x05level\x18\x0f \x01(\x05\x12\x1e\n\x05nodes\x18\n \x03(\x0b\x32\x0f.DynamicSVONodeB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DynamicLayerNodes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_DYNAMICLAYERNODES']._serialized_start=49
  _globals['_DYNAMICLAYERNODES']._serialized_end=115
# @@protoc_insertion_point(module_scope)
