# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EEGMCCNFBHE.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import KJMKJAIFNEC_pb2 as KJMKJAIFNEC__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x45\x45GMCCNFBHE.proto\x1a\x11KJMKJAIFNEC.proto\"[\n\x0b\x45\x45GMCCNFBHE\x12\x13\n\x0b\x43LGHMIPACCO\x18\x02 \x01(\x08\x12\x13\n\x0bIACPFHDIBAH\x18\x03 \x01(\x08\x12\"\n\x0b\x46IAKFNFDPFP\x18\xe7\x07 \x03(\x0b\x32\x0c.KJMKJAIFNECB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EEGMCCNFBHE_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_EEGMCCNFBHE']._serialized_start=40
  _globals['_EEGMCCNFBHE']._serialized_end=131
# @@protoc_insertion_point(module_scope)
