# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EffigyChallengeV2SettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!EffigyChallengeV2SettleInfo.proto\"\xcf\x01\n\x1b\x45\x66\x66igyChallengeV2SettleInfo\x12\x1b\n\x13Unk3300_MHOIIPJKAMN\x18\x0e \x01(\r\x12\x1b\n\x13Unk3300_AKMPCDIKBJD\x18\x05 \x01(\x08\x12\x1b\n\x13Unk3300_ONKPGFOLDFL\x18\x0f \x01(\r\x12\x1b\n\x13Unk3300_PHEIMLOKIJG\x18\n \x01(\r\x12\x1f\n\x17\x63hallengeModeDifficulty\x18\r \x01(\r\x12\x1b\n\x13Unk3300_NGBKNDHJPCP\x18\x01 \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EffigyChallengeV2SettleInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_EFFIGYCHALLENGEV2SETTLEINFO']._serialized_start=38
  _globals['_EFFIGYCHALLENGEV2SETTLEINFO']._serialized_end=245
# @@protoc_insertion_point(module_scope)
