# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EffigyChallengeV2RestartDungeonRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(EffigyChallengeV2RestartDungeonRsp.proto\"5\n\"EffigyChallengeV2RestartDungeonRsp\x12\x0f\n\x07retcode\x18\x03 \x01(\x05\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EffigyChallengeV2RestartDungeonRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_EFFIGYCHALLENGEV2RESTARTDUNGEONRSP']._serialized_start=44
  _globals['_EFFIGYCHALLENGEV2RESTARTDUNGEONRSP']._serialized_end=97
# @@protoc_insertion_point(module_scope)
