# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EKBBAAECGFH.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ExhibitionDisplayInfo_pb2 as ExhibitionDisplayInfo__pb2
import KDECJEOGKOO_pb2 as KDECJEOGKOO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x45KBBAAECGFH.proto\x1a\x1b\x45xhibitionDisplayInfo.proto\x1a\x11KDECJEOGKOO.proto\"\xec\x01\n\x0b\x45KBBAAECGFH\x12\x10\n\x08\x64uration\x18\x0b \x01(\r\x12\x12\n\nbegin_time\x18\n \x01(\r\x12*\n\nscore_list\x18\r \x03(\x0b\x32\x16.ExhibitionDisplayInfo\x12\x11\n\tis_single\x18\t \x01(\x08\x12\x12\n\nplay_index\x18\x02 \x01(\r\x12\x12\n\nstage_type\x18\x0e \x01(\r\x12\x13\n\x0b\x41GPJPHOBGEP\x18\x0f \x01(\x08\x12&\n\x10settle_info_list\x18\x07 \x03(\x0b\x32\x0c.KDECJEOGKOO\x12\x13\n\x0bHJEBIONDCIL\x18\x04 \x03(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EKBBAAECGFH_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_EKBBAAECGFH']._serialized_start=70
  _globals['_EKBBAAECGFH']._serialized_end=306
# @@protoc_insertion_point(module_scope)
