# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EntityFightPropChangeReasonNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PropChangeReason_pb2 as PropChangeReason__pb2
import ChangeHpReason_pb2 as ChangeHpReason__pb2
import ChangeEnergyReason_pb2 as ChangeEnergyReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'EntityFightPropChangeReasonNotify.proto\x1a\x16PropChangeReason.proto\x1a\x14\x43hangeHpReason.proto\x1a\x18\x43hangeEnergyReason.proto\"\xea\x01\n!EntityFightPropChangeReasonNotify\x12\x11\n\tpropDelta\x18\x04 \x01(\x02\x12!\n\x06reason\x18\r \x01(\x0e\x32\x11.PropChangeReason\x12\x10\n\x08\x65ntityId\x18\x0c \x01(\r\x12\x11\n\tparamList\x18\x01 \x03(\r\x12\'\n\x0e\x63hangeHpReason\x18\x06 \x01(\x0e\x32\x0f.ChangeHpReason\x12/\n\x12\x63hangeEnergyReason\x18\x03 \x01(\x0e\x32\x13.ChangeEnergyReason\x12\x10\n\x08propType\x18\x0e \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EntityFightPropChangeReasonNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ENTITYFIGHTPROPCHANGEREASONNOTIFY']._serialized_start=116
  _globals['_ENTITYFIGHTPROPCHANGEREASONNOTIFY']._serialized_end=350
# @@protoc_insertion_point(module_scope)
