# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EntityAbilityInvokeEntry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AbilityInvokeEntry_pb2 as AbilityInvokeEntry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x45ntityAbilityInvokeEntry.proto\x1a\x18\x41\x62ilityInvokeEntry.proto\"R\n\x18\x45ntityAbilityInvokeEntry\x12$\n\x07invokes\x18\x04 \x03(\x0b\x32\x13.AbilityInvokeEntry\x12\x10\n\x08\x65ntityId\x18\t \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EntityAbilityInvokeEntry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ENTITYABILITYINVOKEENTRY']._serialized_start=60
  _globals['_ENTITYABILITYINVOKEENTRY']._serialized_end=142
# @@protoc_insertion_point(module_scope)
