# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EvtAnimatorParameterInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AnimatorParameterValueInfo_pb2 as AnimatorParameterValueInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x45vtAnimatorParameterInfo.proto\x1a AnimatorParameterValueInfo.proto\"\x7f\n\x18\x45vtAnimatorParameterInfo\x12\x10\n\x08\x65ntityId\x18\x0e \x01(\r\x12\x0e\n\x06nameId\x18\x02 \x01(\x05\x12*\n\x05value\x18\x0c \x01(\x0b\x32\x1b.AnimatorParameterValueInfo\x12\x15\n\risServerCache\x18\t \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EvtAnimatorParameterInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_EVTANIMATORPARAMETERINFO']._serialized_start=68
  _globals['_EVTANIMATORPARAMETERINFO']._serialized_end=195
# @@protoc_insertion_point(module_scope)
