# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EvtAiSyncSkillCdNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AiSkillCdInfo_pb2 as AiSkillCdInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x45vtAiSyncSkillCdNotify.proto\x1a\x13\x41iSkillCdInfo.proto\"\x91\x01\n\x16\x45vtAiSyncSkillCdNotify\x12\x37\n\tai_cd_map\x18\x02 \x03(\x0b\x32$.EvtAiSyncSkillCdNotify.AiCdMapEntry\x1a>\n\x0c\x41iCdMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.AiSkillCdInfo:\x02\x38\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EvtAiSyncSkillCdNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY._options = None
  _EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY._serialized_options = b'8\001'
  _globals['_EVTAISYNCSKILLCDNOTIFY']._serialized_start=54
  _globals['_EVTAISYNCSKILLCDNOTIFY']._serialized_end=199
  _globals['_EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY']._serialized_start=137
  _globals['_EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY']._serialized_end=199
# @@protoc_insertion_point(module_scope)
