# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EvtHittingOtherInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AttackResult_pb2 as AttackResult__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x45vtHittingOtherInfo.proto\x1a\x12\x41ttackResult.proto\"L\n\x13\x45vtHittingOtherInfo\x12\x0f\n\x07peer_id\x18\x0c \x01(\r\x12$\n\rattack_result\x18\t \x01(\x0b\x32\r.AttackResultB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EvtHittingOtherInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_EVTHITTINGOTHERINFO']._serialized_start=49
  _globals['_EVTHITTINGOTHERINFO']._serialized_end=125
# @@protoc_insertion_point(module_scope)
