# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExpeditionActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ExpeditionChallengeInfo_pb2 as ExpeditionChallengeInfo__pb2
import ExpeditionPathInfo_pb2 as ExpeditionPathInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ExpeditionActivityDetailInfo.proto\x1a\x1d\x45xpeditionChallengeInfo.proto\x1a\x18\x45xpeditionPathInfo.proto\"\xe3\x01\n\x1c\x45xpeditionActivityDetailInfo\x12\x35\n\x13\x63hallenge_info_list\x18\x06 \x03(\x0b\x32\x18.ExpeditionChallengeInfo\x12\x13\n\x0bGAAPPKJCHMG\x18\x01 \x01(\r\x12+\n\x0epath_info_list\x18\x05 \x03(\x0b\x32\x13.ExpeditionPathInfo\x12\x1a\n\x12\x63ontent_close_time\x18\x0c \x01(\r\x12\x13\n\x0b\x42NCAJGILFGD\x18\x04 \x01(\r\x12\x19\n\x11is_content_closed\x18\t \x01(\x08\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExpeditionActivityDetailInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_EXPEDITIONACTIVITYDETAILINFO']._serialized_start=96
  _globals['_EXPEDITIONACTIVITYDETAILINFO']._serialized_end=323
# @@protoc_insertion_point(module_scope)
