# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FCFNMEJMONG.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x46\x43\x46NMEJMONG.proto\"}\n\x0b\x46\x43\x46NMEJMONG\x12\x16\n\x0emusic_basic_id\x18\x0b \x01(\r\x12\x15\n\ris_new_record\x18\x03 \x01(\x08\x12\x0f\n\x07retcode\x18\r \x01(\x05\x12\x10\n\x08ugc_guid\x18\x05 \x01(\x04\x12\x1c\n\x14is_unlock_next_level\x18\x02 \x01(\x08\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FCFNMEJMONG_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_FCFNMEJMONG']._serialized_start=21
  _globals['_FCFNMEJMONG']._serialized_end=146
# @@protoc_insertion_point(module_scope)
