# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FDOHOGJAGDN.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x46\x44OHOGJAGDN.proto\"7\n\x0b\x46\x44OHOGJAGDN\x12\x13\n\x0bMBNLNOFPLLA\x18\t \x01(\r\x12\x13\n\x0b\x41HAIAIPGFDN\x18\n \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FDOHOGJAGDN_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_FDOHOGJAGDN']._serialized_start=21
  _globals['_FDOHOGJAGDN']._serialized_end=76
# @@protoc_insertion_point(module_scope)
