# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FFBGCLGOCDG.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x46\x46\x42GCLGOCDG.proto\x1a\x0cVector.proto\"h\n\x0b\x46\x46\x42GCLGOCDG\x12\x13\n\x0b\x42\x45PDAGJHGNK\x18\x07 \x01(\r\x12\x1c\n\x0bHOHCJADGKFD\x18\x06 \x01(\x0b\x32\x07.Vector\x12\x13\n\x0b\x45\x42MAEIDEILG\x18\t \x01(\r\x12\x11\n\tentity_id\x18\x02 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FFBGCLGOCDG_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_FFBGCLGOCDG']._serialized_start=35
  _globals['_FFBGCLGOCDG']._serialized_end=139
# @@protoc_insertion_point(module_scope)
