# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FireworksReformParamType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x46ireworksReformParamType.proto*\xea\x01\n\x18\x46ireworksReformParamType\x12\x1f\n\x1b\x46IREWORKS_REFORM_PARAM_NONE\x10\x00\x12 \n\x1c\x46IREWORKS_REFORM_PARAM_COLOR\x10\x01\x12!\n\x1d\x46IREWORKS_REFORM_PARAM_HEIGHT\x10\x02\x12\x1f\n\x1b\x46IREWORKS_REFORM_PARAM_SIZE\x10\x03\x12\"\n\x1e\x46IREWORKS_REFORM_PARAM_DENSITY\x10\x04\x12#\n\x1f\x46IREWORKS_REFORM_PARAM_ROTATION\x10\x05\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FireworksReformParamType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_FIREWORKSREFORMPARAMTYPE']._serialized_start=35
  _globals['_FIREWORKSREFORMPARAMTYPE']._serialized_end=269
# @@protoc_insertion_point(module_scope)
