# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FireworksLaunchSchemeData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FireworksLaunchParam_pb2 as FireworksLaunchParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x46ireworksLaunchSchemeData.proto\x1a\x1a\x46ireworksLaunchParam.proto\"v\n\x19\x46ireworksLaunchSchemeData\x12\x10\n\x08schemeId\x18\x02 \x01(\r\x12.\n\x0flaunchParamList\x18\r \x03(\x0b\x32\x15.FireworksLaunchParam\x12\x17\n\x0f\x66ireworksIdList\x18\x01 \x03(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FireworksLaunchSchemeData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_FIREWORKSLAUNCHSCHEMEDATA']._serialized_start=63
  _globals['_FIREWORKSLAUNCHSCHEMEDATA']._serialized_end=181
# @@protoc_insertion_point(module_scope)
