# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FishingGallerySettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FishingGallerySettleInfo_pb2 as FishingGallerySettleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n FishingGallerySettleNotify.proto\x1a\x1e\x46ishingGallerySettleInfo.proto\"r\n\x1a\x46ishingGallerySettleNotify\x12.\n\x0bsettle_info\x18\x05 \x01(\x0b\x32\x19.FishingGallerySettleInfo\x12\x10\n\x08level_id\x18\x0e \x01(\r\x12\x12\n\ngallery_id\x18\x0c \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FishingGallerySettleNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_FISHINGGALLERYSETTLENOTIFY']._serialized_start=68
  _globals['_FISHINGGALLERYSETTLENOTIFY']._serialized_end=182
# @@protoc_insertion_point(module_scope)
