# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FishEscapeReason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x46ishEscapeReason.proto*Y\n\x10\x46ishEscapeReason\x12\x14\n\x10\x46ISN_ESCAPE_NONE\x10\x00\x12\x17\n\x13\x46ISH_ESCAPE_SHOCKED\x10\x01\x12\x16\n\x12\x46ISH_ESCAPE_UNHOOK\x10\x02\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FishEscapeReason_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_FISHESCAPEREASON']._serialized_start=26
  _globals['_FISHESCAPEREASON']._serialized_end=115
# @@protoc_insertion_point(module_scope)
