# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FleurFairPlayerStatInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ProfilePicture_pb2 as ProfilePicture__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x46leurFairPlayerStatInfo.proto\x1a\x14ProfilePicture.proto\"\xaa\x01\n\x17\x46leurFairPlayerStatInfo\x12(\n\x0fprofile_picture\x18\x0b \x01(\x0b\x32\x0f.ProfilePicture\x12\x11\n\tonline_id\x18\x02 \x01(\t\x12\x12\n\nhead_image\x18\x0e \x01(\r\x12\x11\n\tnick_name\x18\r \x01(\t\x12\x0b\n\x03uid\x18\x0c \x01(\r\x12\r\n\x05param\x18\x04 \x01(\x05\x12\x0f\n\x07stat_id\x18\x01 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FleurFairPlayerStatInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_FLEURFAIRPLAYERSTATINFO']._serialized_start=56
  _globals['_FLEURFAIRPLAYERSTATINFO']._serialized_end=226
# @@protoc_insertion_point(module_scope)
