# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForgeQueueManipulateType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x46orgeQueueManipulateType.proto*v\n\x18\x46orgeQueueManipulateType\x12.\n*FORGE_QUEUE_MANIPULATE_TYPE_RECEIVE_OUTPUT\x10\x00\x12*\n&FORGE_QUEUE_MANIPULATE_TYPE_STOP_FORGE\x10\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ForgeQueueManipulateType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_FORGEQUEUEMANIPULATETYPE']._serialized_start=34
  _globals['_FORGEQUEUEMANIPULATETYPE']._serialized_end=152
# @@protoc_insertion_point(module_scope)
