# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForgeQueueData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x46orgeQueueData.proto\"\xab\x01\n\x0e\x46orgeQueueData\x12\x0f\n\x07\x66orgeId\x18\x06 \x01(\r\x12\x13\n\x0b\x66inishCount\x18\x01 \x01(\r\x12\x0f\n\x07queueId\x18\t \x01(\r\x12\x15\n\runfinishCount\x18\x08 \x01(\r\x12\x1c\n\x14totalFinishTimestamp\x18\x0b \x01(\r\x12\x10\n\x08\x61vatarId\x18\x0c \x01(\r\x12\x1b\n\x13nextFinishTimestamp\x18\x02 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ForgeQueueData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_FORGEQUEUEDATA']._serialized_start=25
  _globals['_FORGEQUEUEDATA']._serialized_end=196
# @@protoc_insertion_point(module_scope)
