# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForgeQueueManipulateRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ForgeQueueManipulateType_pb2 as ForgeQueueManipulateType__pb2
import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x46orgeQueueManipulateRsp.proto\x1a\x1e\x46orgeQueueManipulateType.proto\x1a\x0fItemParam.proto\"\xce\x01\n\x17\x46orgeQueueManipulateRsp\x12\"\n\x0ereturnItemList\x18\x03 \x03(\x0b\x32\n.ItemParam\x12\x31\n\x0emanipulateType\x18\x07 \x01(\x0e\x32\x19.ForgeQueueManipulateType\x12\'\n\x13\x65xtraOutputItemList\x18\r \x03(\x0b\x32\n.ItemParam\x12\"\n\x0eoutputItemList\x18\x0c \x03(\x0b\x32\n.ItemParam\x12\x0f\n\x07retcode\x18\x05 \x01(\x05\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ForgeQueueManipulateRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_FORGEQUEUEMANIPULATERSP']._serialized_start=83
  _globals['_FORGEQUEUEMANIPULATERSP']._serialized_end=289
# @@protoc_insertion_point(module_scope)
