# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForwardType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x46orwardType.proto*\xeb\x01\n\x0b\x46orwardType\x12\x11\n\rFORWARD_LOCAL\x10\x00\x12\x12\n\x0e\x46ORWARD_TO_ALL\x10\x01\x12\x1d\n\x19\x46ORWARD_TO_ALL_EXCEPT_CUR\x10\x02\x12\x13\n\x0f\x46ORWARD_TO_HOST\x10\x03\x12\x18\n\x14\x46ORWARD_TO_ALL_GUEST\x10\x04\x12\x13\n\x0f\x46ORWARD_TO_PEER\x10\x05\x12\x14\n\x10\x46ORWARD_TO_PEERS\x10\x06\x12\x17\n\x13\x46ORWARD_ONLY_SERVER\x10\x07\x12#\n\x1f\x46ORWARD_TO_ALL_EXIST_EXCEPT_CUR\x10\x08\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ForwardType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_FORWARDTYPE']._serialized_start=22
  _globals['_FORWARDTYPE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
