# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FoundationStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x46oundationStatus.proto*\x87\x01\n\x10\x46oundationStatus\x12\x1a\n\x16\x46OUNDATION_STATUS_NONE\x10\x00\x12\x1a\n\x16\x46OUNDATION_STATUS_INIT\x10\x01\x12\x1e\n\x1a\x46OUNDATION_STATUS_BUILDING\x10\x02\x12\x1b\n\x17\x46OUNDATION_STATUS_BUILT\x10\x03\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FoundationStatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_FOUNDATIONSTATUS']._serialized_start=27
  _globals['_FOUNDATIONSTATUS']._serialized_end=162
# @@protoc_insertion_point(module_scope)
