# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FPFHGDCLELH.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import OPDLLIJJGFB_pb2 as OPDLLIJJGFB__pb2
import PMJLNPPJJCI_pb2 as PMJLNPPJJCI__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x46PFHGDCLELH.proto\x1a\x11OPDLLIJJGFB.proto\x1a\x11PMJLNPPJJCI.proto\"a\n\x0b\x46PFHGDCLELH\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x0bGMIHFCGDEJH\x18\x02 \x03(\x0b\x32\x0c.OPDLLIJJGFB\x12!\n\x0bPNFIHGPGNKD\x18\x03 \x01(\x0b\x32\x0c.PMJLNPPJJCIB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FPFHGDCLELH_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_FPFHGDCLELH']._serialized_start=59
  _globals['_FPFHGDCLELH']._serialized_end=156
# @@protoc_insertion_point(module_scope)
