# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FungusFighterRuntimeDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FungusTrainingProgressDetail_pb2 as FungusTrainingProgressDetail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$FungusFighterRuntimeDataNotify.proto\x1a\"FungusTrainingProgressDetail.proto\"W\n\x1e\x46ungusFighterRuntimeDataNotify\x12\x35\n\x0eprogressDetail\x18\x0e \x01(\x0b\x32\x1d.FungusTrainingProgressDetailB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FungusFighterRuntimeDataNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_FUNGUSFIGHTERRUNTIMEDATANOTIFY']._serialized_start=76
  _globals['_FUNGUSFIGHTERRUNTIMEDATANOTIFY']._serialized_end=163
# @@protoc_insertion_point(module_scope)
