# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GadgetGeneralRewardInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dGadgetGeneralRewardInfo.proto\x1a\x0fItemParam.proto\"\x88\x01\n\x17GadgetGeneralRewardInfo\x12\r\n\x05resin\x18\x01 \x01(\r\x12\x10\n\x08\x64\x65\x61\x64Time\x18\x02 \x01(\r\x12\x15\n\rremainUidList\x18\x03 \x03(\r\x12\x16\n\x0equalifyUidList\x18\x04 \x03(\r\x12\x1d\n\titemParam\x18\x05 \x01(\x0b\x32\n.ItemParamB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GadgetGeneralRewardInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GADGETGENERALREWARDINFO']._serialized_start=51
  _globals['_GADGETGENERALREWARDINFO']._serialized_end=187
# @@protoc_insertion_point(module_scope)
