# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GadgetPlayDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGadgetPlayDataNotify.proto\"N\n\x14GadgetPlayDataNotify\x12\x11\n\tplay_type\x18\x02 \x01(\r\x12\x10\n\x08progress\x18\x08 \x01(\r\x12\x11\n\tentity_id\x18\n \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GadgetPlayDataNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_GADGETPLAYDATANOTIFY']._serialized_start=30
  _globals['_GADGETPLAYDATANOTIFY']._serialized_end=108
# @@protoc_insertion_point(module_scope)
