# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GadgetPlayStopNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GadgetPlayUidInfo_pb2 as GadgetPlayUidInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGadgetPlayStopNotify.proto\x1a\x17GadgetPlayUidInfo.proto\"\x99\x01\n\x14GadgetPlayStopNotify\x12\x11\n\tcost_time\x18\x0c \x01(\r\x12\r\n\x05score\x18\t \x01(\r\x12)\n\ruid_info_list\x18\x05 \x03(\x0b\x32\x12.GadgetPlayUidInfo\x12\x11\n\tplay_type\x18\x07 \x01(\r\x12\x11\n\tentity_id\x18\x01 \x01(\r\x12\x0e\n\x06is_win\x18\x08 \x01(\x08\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GadgetPlayStopNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_GADGETPLAYSTOPNOTIFY']._serialized_start=56
  _globals['_GADGETPLAYSTOPNOTIFY']._serialized_end=209
# @@protoc_insertion_point(module_scope)
