# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GalleryStartNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ADMIOIMGPLK_pb2 as ADMIOIMGPLK__pb2
import GalleryFlowerStartParam_pb2 as GalleryFlowerStartParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18GalleryStartNotify.proto\x1a\x11\x41\x44MIOIMGPLK.proto\x1a\x1dGalleryFlowerStartParam.proto\"\xee\x01\n\x12GalleryStartNotify\x12\x10\n\x08\x65nd_time\x18\x08 \x01(\r\x12\x12\n\nstart_time\x18\x03 \x01(\r\x12\x14\n\x0cplayer_count\x18\t \x01(\r\x12\x12\n\ngallery_id\x18\x0b \x01(\r\x12\x11\n\towner_uid\x18\x0f \x01(\r\x12\x36\n\x12\x66lower_start_param\x18\x05 \x01(\x0b\x32\x18.GalleryFlowerStartParamH\x00\x12\x33\n\x1b\x65lectrohercules_start_param\x18\r \x01(\x0b\x32\x0c.ADMIOIMGPLKH\x00\x42\x08\n\x06\x64\x65tailB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GalleryStartNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_GALLERYSTARTNOTIFY']._serialized_start=79
  _globals['_GALLERYSTARTNOTIFY']._serialized_end=317
# @@protoc_insertion_point(module_scope)
