# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGChallengeUpdateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGDuelChallenge_pb2 as GCGDuelChallenge__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eGCGChallengeUpdateNotify.proto\x1a\x16GCGDuelChallenge.proto\"S\n\x18GCGChallengeUpdateNotify\x12$\n\tchallenge\x18\x04 \x01(\x0b\x32\x11.GCGDuelChallenge\x12\x11\n\tserverSeq\x18\t \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGChallengeUpdateNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GCGCHALLENGEUPDATENOTIFY']._serialized_start=58
  _globals['_GCGCHALLENGEUPDATENOTIFY']._serialized_end=141
# @@protoc_insertion_point(module_scope)
