# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGMsgCostDice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGReason_pb2 as GCGReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14GCGMsgCostDice.proto\x1a\x0fGCGReason.proto\"c\n\x0eGCGMsgCostDice\x12\x15\n\rcontroller_id\x18\x0f \x01(\r\x12\x1e\n\x16select_dice_index_list\x18\x01 \x03(\r\x12\x1a\n\x06reason\x18\x0b \x01(\x0e\x32\n.GCGReasonB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGMsgCostDice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_GCGMSGCOSTDICE']._serialized_start=41
  _globals['_GCGMSGCOSTDICE']._serialized_end=140
# @@protoc_insertion_point(module_scope)
