# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGSkillPreviewNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGChangeOnstageInfo_pb2 as GCGChangeOnstageInfo__pb2
import GCGSkillPreviewInfo_pb2 as GCGSkillPreviewInfo__pb2
import GCGSkillPreviewPlayCardInfo_pb2 as GCGSkillPreviewPlayCardInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bGCGSkillPreviewNotify.proto\x1a\x1aGCGChangeOnstageInfo.proto\x1a\x19GCGSkillPreviewInfo.proto\x1a!GCGSkillPreviewPlayCardInfo.proto\"\xe3\x01\n\x15GCGSkillPreviewNotify\x12\x37\n\x18\x63hangeOnstagePreviewList\x18\x02 \x03(\x0b\x32\x15.GCGChangeOnstageInfo\x12\x14\n\x0c\x63ontrollerId\x18\x03 \x01(\r\x12.\n\x10skillPreviewList\x18\x06 \x03(\x0b\x32\x14.GCGSkillPreviewInfo\x12\x32\n\x0cplayCardList\x18\t \x03(\x0b\x32\x1c.GCGSkillPreviewPlayCardInfo\x12\x17\n\x0fonstageCardGuid\x18\n \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGSkillPreviewNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GCGSKILLPREVIEWNOTIFY']._serialized_start=122
  _globals['_GCGSKILLPREVIEWNOTIFY']._serialized_end=349
# @@protoc_insertion_point(module_scope)
