# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGStartChallengeByCheckRewardRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import uint32_pb2 as uint32__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'GCGStartChallengeByCheckRewardRsp.proto\x1a\x0cuint32.proto\"o\n!GCGStartChallengeByCheckRewardRsp\x12\x13\n\x0b\x62phdgokdnnk\x18\x07 \x01(\x08\x12\x17\n\x0fnextRefreshTime\x18\t \x01(\r\x12\x1c\n\x14\x65xceededItemTypeList\x18\x08 \x03(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGStartChallengeByCheckRewardRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GCGSTARTCHALLENGEBYCHECKREWARDRSP']._serialized_start=57
  _globals['_GCGSTARTCHALLENGEBYCHECKREWARDRSP']._serialized_end=168
# @@protoc_insertion_point(module_scope)
