# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGSkillPreviewCardInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGZoneType_pb2 as GCGZoneType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dGCGSkillPreviewCardInfo.proto\x1a\x11GCGZoneType.proto\"\x99\x01\n\x17GCGSkillPreviewCardInfo\x12\x1e\n\x08zoneType\x18\r \x01(\x0e\x32\x0c.GCGZoneType\x12\x14\n\x0c\x63ontrollerId\x18\x01 \x01(\r\x12\x15\n\rownerCardGuid\x18\x07 \x01(\r\x12\x10\n\x08\x63\x61rdGuid\x18\x0c \x01(\r\x12\x0f\n\x07retcode\x18\n \x01(\r\x12\x0e\n\x06\x63\x61rdId\x18\x05 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGSkillPreviewCardInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GCGSKILLPREVIEWCARDINFO']._serialized_start=53
  _globals['_GCGSKILLPREVIEWCARDINFO']._serialized_end=206
# @@protoc_insertion_point(module_scope)
