# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GCGTavernNpcInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16GCGTavernNpcInfo.proto\"H\n\x10GCGTavernNpcInfo\x12\x10\n\x08level_id\x18\x0e \x01(\r\x12\n\n\x02id\x18\x08 \x01(\r\x12\x16\n\x0escene_point_id\x18\n \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GCGTavernNpcInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_GCGTAVERNNPCINFO']._serialized_start=26
  _globals['_GCGTAVERNNPCINFO']._serialized_end=98
# @@protoc_insertion_point(module_scope)
