# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GearLevelData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13GearLevelData.proto\"\x90\x01\n\rGearLevelData\x12\x1b\n\x13Unk3300_DFGHKDBENED\x18\x01 \x01(\r\x12\x10\n\x08openTime\x18\x04 \x01(\r\x12\x0f\n\x07levelId\x18\x07 \x01(\r\x12\x1b\n\x13Unk3300_FIKPLGJIBGP\x18\x0c \x01(\r\x12\x12\n\nisFinished\x18\r \x01(\x08\x12\x0e\n\x06isOpen\x18\t \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GearLevelData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GEARLEVELDATA']._serialized_start=24
  _globals['_GEARLEVELDATA']._serialized_end=168
# @@protoc_insertion_point(module_scope)
