# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetAllMailResultNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MailData_pb2 as MailData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGetAllMailResultNotify.proto\x1a\x0eMailData.proto\"\x9c\x01\n\x16GetAllMailResultNotify\x12\x0f\n\x07retcode\x18\x06 \x01(\x05\x12\x13\n\x0b\x46\x43GFGPDOKOH\x18\x01 \x01(\r\x12\x1c\n\tmail_list\x18\n \x03(\x0b\x32\t.MailData\x12\x13\n\x0btransaction\x18\x05 \x01(\t\x12\x14\n\x0cis_collected\x18\x08 \x01(\x08\x12\x13\n\x0bGKAOFKGNGGO\x18\r \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetAllMailResultNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_GETALLMAILRESULTNOTIFY']._serialized_start=49
  _globals['_GETALLMAILRESULTNOTIFY']._serialized_end=205
# @@protoc_insertion_point(module_scope)
