# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetOpActivityInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import OpActivityInfo_pb2 as OpActivityInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGetOpActivityInfoRsp.proto\x1a\x14OpActivityInfo.proto\"T\n\x14GetOpActivityInfoRsp\x12+\n\x12opActivityInfoList\x18\x0b \x03(\x0b\x32\x0f.OpActivityInfo\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetOpActivityInfoRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GETOPACTIVITYINFORSP']._serialized_start=52
  _globals['_GETOPACTIVITYINFORSP']._serialized_end=136
# @@protoc_insertion_point(module_scope)
