# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetPlayerTokenRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bytes_pb2 as bytes__pb2
import StopServer_pb2 as StopServer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GetPlayerTokenRsp.proto\x1a\x0b\x62ytes.proto\x1a\x10StopServer.proto\"\xc8\x05\n\x11GetPlayerTokenRsp\x12\x15\n\x0csubChannelId\x18\xfb\x06 \x01(\r\x12\r\n\x05token\x18\x06 \x01(\t\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x11\n\tsecretKey\x18\x0c \x01(\t\x12\x13\n\x0b\x61\x63\x63ountType\x18\x03 \x01(\r\x12\x0b\n\x03msg\x18\n \x01(\t\x12\x1c\n\x13Unk3300_AJBBIPFMBEL\x18\x95\x05 \x01(\x08\x12\x19\n\x11securityCmdBuffer\x18\r \x01(\x0c\x12\x0f\n\x07retcode\x18\x0f \x01(\x05\x12\x14\n\x0c\x65xtraBinData\x18\x0e \x01(\x0c\x12\x1f\n\x16\x63lientVersionRandomKey\x18\x96\x0c \x01(\t\x12\x14\n\x0b\x63ountryCode\x18\xa8\x0f \x01(\t\x12\x0e\n\x05keyId\x18\xd3\x0f \x01(\r\x12\x11\n\x08\x62irthday\x18\xb3\x0b \x01(\t\x12\r\n\x05gmUid\x18\x05 \x01(\r\x12\x15\n\rsecretKeySeed\x18\x08 \x01(\x04\x12\x17\n\x0f\x62lackUidEndTime\x18\x02 \x01(\r\x12\x12\n\tchannelId\x18\xcc\n \x01(\r\x12\x14\n\x0bregPlatform\x18\xce\x0c \x01(\r\x12\x14\n\x0cplatformType\x18\x0b \x01(\r\x12\x0f\n\x07isGuest\x18\x04 \x01(\x08\x12\x1f\n\x16\x66inishCollectionIdList\x18\xb6\x0e \x03(\r\x12\x0c\n\x03tag\x18\xc0\n \x01(\r\x12\x12\n\naccountUid\x18\t \x01(\t\x12\x1a\n\x12isProficientPlayer\x18\x07 \x01(\x08\x12\r\n\x04sign\x18\xc9\x0f \x01(\t\x12 \n\nstopServer\x18\xdb\x02 \x01(\x0b\x32\x0b.StopServer\x12\x0e\n\x05psnId\x18\x85\n \x01(\t\x12\x16\n\rcloudClientIp\x18\xc9\x0b \x01(\r\x12\x13\n\x0b\x63lientIpStr\x18@ \x01(\t\x12\x16\n\rserverRandKey\x18\x8c\x0b \x01(\t\x12\x1c\n\x13Unk3300_CFBHAHOHDKC\x18\xff\x0c \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetPlayerTokenRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GETPLAYERTOKENRSP']._serialized_start=59
  _globals['_GETPLAYERTOKENRSP']._serialized_end=771
# @@protoc_insertion_point(module_scope)
