# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetPlayerTokenReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GetPlayerTokenReq.proto\"\xc5\x03\n\x11GetPlayerTokenReq\x12\x12\n\nchannel_id\x18\x03 \x01(\r\x12\x14\n\x0c\x61\x63\x63ount_type\x18\x02 \x01(\r\x12\x15\n\raccount_token\x18\r \x01(\t\x12\x10\n\x08\x62irthday\x18) \x01(\t\x12\x15\n\rclient_ip_str\x18\x08 \x01(\t\x12\x10\n\x08is_guest\x18\n \x01(\x08\x12\x11\n\tonline_id\x18\x0e \x01(\t\x12\x18\n\x0f\x63lient_rand_key\x18\xf6\x0f \x01(\t\x12\x14\n\x0b\x42GELCCHCJDG\x18\x8e\x0e \x01(\r\x12\x13\n\x0b\x61\x63\x63ount_uid\x18\x07 \x01(\t\x12\x0e\n\x06psn_id\x18\x0f \x01(\t\x12\x13\n\x0bHBEOMFDDEPG\x18\x0b \x01(\t\x12\x14\n\x0b\x44\x44\x42JAFAFLNP\x18\x9d\x08 \x01(\t\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x14\n\x0b\x44MBKJKNPKBC\x18\xfe\x0c \x01(\r\x12\x16\n\x0esub_channel_id\x18\x04 \x01(\r\x12\x15\n\rplatform_type\x18\x0c \x01(\r\x12\x13\n\x0b\x45\x44GJFDAKLKN\x18\t \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x06 \x01(\t\x12\x13\n\x0bGHBLLEHOHNP\x18\x05 \x01(\r\x12\x0f\n\x06key_id\x18\x93\x07 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetPlayerTokenReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_GETPLAYERTOKENREQ']._serialized_start=28
  _globals['_GETPLAYERTOKENREQ']._serialized_end=481
# @@protoc_insertion_point(module_scope)
