# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetParentQuestVideoKeyRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fGetParentQuestVideoKeyRsp.proto\"U\n\x19GetParentQuestVideoKeyRsp\x12\x10\n\x08videoKey\x18\x02 \x01(\x04\x12\x0f\n\x07retcode\x18\t \x01(\x05\x12\x15\n\rparentQuestId\x18\x0b \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetParentQuestVideoKeyRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GETPARENTQUESTVIDEOKEYRSP']._serialized_start=35
  _globals['_GETPARENTQUESTVIDEOKEYRSP']._serialized_end=120
# @@protoc_insertion_point(module_scope)
