# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetQuestTalkHistoryRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGetQuestTalkHistoryRsp.proto\"X\n\x16GetQuestTalkHistoryRsp\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x12\x17\n\x0fparent_quest_id\x18\t \x01(\r\x12\x14\n\x0ctalk_id_list\x18\x05 \x03(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetQuestTalkHistoryRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_GETQUESTTALKHISTORYRSP']._serialized_start=32
  _globals['_GETQUESTTALKHISTORYRSP']._serialized_end=120
# @@protoc_insertion_point(module_scope)
