# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetScenePointRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16GetScenePointRsp.proto\"\xd1\x02\n\x10GetScenePointRsp\x12\x17\n\x0flockedPointList\x18\x07 \x03(\r\x12#\n\x1bnotInteractDungeonEntryList\x18\n \x03(\r\x12\x0f\n\x07retcode\x18\x02 \x01(\x05\x12#\n\x1btoBeExploreDungeonEntryList\x18\r \x03(\r\x12\x11\n\tbelongUid\x18\x06 \x01(\r\x12\x15\n\rhidePointList\x18\x03 \x03(\r\x12\x16\n\x0eunlockAreaList\x18\t \x03(\r\x12\x19\n\x11unlockedPointList\x18\x0c \x03(\r\x12#\n\x1bnotExploredDungeonEntryList\x18\x04 \x03(\r\x12\x17\n\x0funhidePointList\x18\x05 \x03(\r\x12\x0f\n\x07sceneId\x18\x0e \x01(\r\x12\x1d\n\x15groupUnlimitPointList\x18\x01 \x03(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetScenePointRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GETSCENEPOINTRSP']._serialized_start=27
  _globals['_GETSCENEPOINTRSP']._serialized_end=364
# @@protoc_insertion_point(module_scope)
