# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetSceneNpcPositionRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import NpcPositionInfo_pb2 as NpcPositionInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGetSceneNpcPositionRsp.proto\x1a\x15NpcPositionInfo.proto\"a\n\x16GetSceneNpcPositionRsp\x12\x0f\n\x07sceneId\x18\r \x01(\r\x12%\n\x0bnpcInfoList\x18\x06 \x03(\x0b\x32\x10.NpcPositionInfo\x12\x0f\n\x07retcode\x18\x03 \x01(\x05\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetSceneNpcPositionRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GETSCENENPCPOSITIONRSP']._serialized_start=55
  _globals['_GETSCENENPCPOSITIONRSP']._serialized_end=152
# @@protoc_insertion_point(module_scope)
