# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GGBMIADMOHH.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LLOKNKLJFHI_pb2 as LLOKNKLJFHI__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11GGBMIADMOHH.proto\x1a\x11LLOKNKLJFHI.proto\"I\n\x0bGGBMIADMOHH\x12%\n\x0fstage_data_list\x18\x0c \x03(\x0b\x32\x0c.LLOKNKLJFHI\x12\x13\n\x0bIHCMMNBKCFH\x18\x0f \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GGBMIADMOHH_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_GGBMIADMOHH']._serialized_start=40
  _globals['_GGBMIADMOHH']._serialized_end=113
# @@protoc_insertion_point(module_scope)
