# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GravenInnocenceRaceLevelInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"GravenInnocenceRaceLevelInfo.proto\"Q\n\x1cGravenInnocenceRaceLevelInfo\x12\x0f\n\x07levelId\x18\x07 \x01(\r\x12\x0e\n\x06isOpen\x18\r \x01(\x08\x12\x10\n\x08maxScore\x18\x0f \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GravenInnocenceRaceLevelInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GRAVENINNOCENCERACELEVELINFO']._serialized_start=38
  _globals['_GRAVENINNOCENCERACELEVELINFO']._serialized_end=119
# @@protoc_insertion_point(module_scope)
