# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GravenInnocencePhotoInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GravenInnocencePhotoObjectInfo_pb2 as GravenInnocencePhotoObjectInfo__pb2
import GravenInnocencePhotoStageInfo_pb2 as GravenInnocencePhotoStageInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eGravenInnocencePhotoInfo.proto\x1a$GravenInnocencePhotoObjectInfo.proto\x1a#GravenInnocencePhotoStageInfo.proto\"\x8a\x01\n\x18GravenInnocencePhotoInfo\x12\x37\n\x0eobjectInfoList\x18\n \x03(\x0b\x32\x1f.GravenInnocencePhotoObjectInfo\x12\x35\n\rstageInfoList\x18\x03 \x03(\x0b\x32\x1e.GravenInnocencePhotoStageInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GravenInnocencePhotoInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GRAVENINNOCENCEPHOTOINFO']._serialized_start=110
  _globals['_GRAVENINNOCENCEPHOTOINFO']._serialized_end=248
# @@protoc_insertion_point(module_scope)
