# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupLinkBundle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15GroupLinkBundle.proto\x1a\x0cVector.proto\"\x86\x01\n\x0fGroupLinkBundle\x12\x13\n\x0bisActivated\x18\x07 \x01(\x08\x12\x17\n\x06\x63\x65nter\x18\x06 \x01(\x0b\x32\x07.Vector\x12\x0f\n\x07sceneId\x18\x08 \x01(\r\x12\x0e\n\x06radius\x18\r \x01(\r\x12\x12\n\nisShowMark\x18\x0c \x01(\x08\x12\x10\n\x08\x62undleId\x18\t \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupLinkBundle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_GROUPLINKBUNDLE']._serialized_start=40
  _globals['_GROUPLINKBUNDLE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
