# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HEHODLHCPEL.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11HEHODLHCPEL.proto\x1a\x0cVector.proto\"[\n\x0bHEHODLHCPEL\x12\x10\n\x08\x65ntityId\x18\n \x01(\r\x12\x1c\n\x0bglbmapjdhpc\x18\x05 \x01(\x0b\x32\x07.Vector\x12\x1c\n\x0bgnanpemiogh\x18\t \x01(\x0b\x32\x07.VectorB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HEHODLHCPEL_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HEHODLHCPEL']._serialized_start=35
  _globals['_HEHODLHCPEL']._serialized_end=126
# @@protoc_insertion_point(module_scope)
