# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HFDGDGLGEEE.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GMJDGJIDDCI_pb2 as GMJDGJIDDCI__pb2
import GJPHKJFFMOM_pb2 as GJPHKJFFMOM__pb2
import LLIJLJFHGBD_pb2 as LLIJLJFHGBD__pb2
import PLDKICHAHEB_pb2 as PLDKICHAHEB__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11HFDGDGLGEEE.proto\x1a\x11GMJDGJIDDCI.proto\x1a\x11GJPHKJFFMOM.proto\x1a\x11LLIJLJFHGBD.proto\x1a\x11PLDKICHAHEB.proto\"\xc2\x01\n\x0bHFDGDGLGEEE\x12\x12\n\ncreateTime\x18\x01 \x01(\t\x12!\n\x0bpakoigkhjal\x18\x02 \x03(\x0b\x32\x0c.LLIJLJFHGBD\x12\x13\n\x0bknmgmjklfob\x18\x03 \x03(\t\x12!\n\x0bjkfdibhoggm\x18\x04 \x03(\x0b\x32\x0c.PLDKICHAHEB\x12!\n\x0bojmkoemmlpa\x18\x05 \x01(\x0b\x32\x0c.GMJDGJIDDCI\x12!\n\x0bidbdfgaalao\x18\x06 \x01(\x0e\x32\x0c.GJPHKJFFMOMB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HFDGDGLGEEE_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HFDGDGLGEEE']._serialized_start=98
  _globals['_HFDGDGLGEEE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
