# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HNNNJJPLLFN.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11HNNNJJPLLFN.proto\x1a\x0cVector.proto\"I\n\x0bHNNNJJPLLFN\x12\x0e\n\x06roomId\x18\t \x01(\r\x12\x14\n\x03rot\x18\x02 \x01(\x0b\x32\x07.Vector\x12\x14\n\x03pos\x18\x0f \x01(\x0b\x32\x07.VectorB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HNNNJJPLLFN_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HNNNJJPLLFN']._serialized_start=35
  _globals['_HNNNJJPLLFN']._serialized_end=108
# @@protoc_insertion_point(module_scope)
