# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeAvatarSummonEventInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fHomeAvatarSummonEventInfo.proto\"\x8b\x01\n\x19HomeAvatarSummonEventInfo\x12\x0e\n\x06suitId\x18\x04 \x01(\r\x12\x16\n\x0erandomPosition\x18\x02 \x01(\r\x12\x0f\n\x07\x65ventId\x18\x03 \x01(\r\x12\x10\n\x08\x61vatarId\x18\x0c \x01(\r\x12\x15\n\reventOverTime\x18\x0e \x01(\r\x12\x0c\n\x04guid\x18\x01 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeAvatarSummonEventInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HOMEAVATARSUMMONEVENTINFO']._serialized_start=36
  _globals['_HOMEAVATARSUMMONEVENTINFO']._serialized_end=175
# @@protoc_insertion_point(module_scope)
