# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeBalloonGalleryRecord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeGroupPlayerInfo_pb2 as HomeGroupPlayerInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eHomeBalloonGalleryRecord.proto\x1a\x19HomeGroupPlayerInfo.proto\"x\n\x18HomeBalloonGalleryRecord\x12\x10\n\x08hitCount\x18\x02 \x01(\r\x12\r\n\x05score\x18\x0c \x01(\r\x12(\n\nplayerInfo\x18\x0b \x01(\x0b\x32\x14.HomeGroupPlayerInfo\x12\x11\n\ttimestamp\x18\r \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeBalloonGalleryRecord_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HOMEBALLOONGALLERYRECORD']._serialized_start=61
  _globals['_HOMEBALLOONGALLERYRECORD']._serialized_end=181
# @@protoc_insertion_point(module_scope)
