# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeSeekFurnitureAllRecord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeSeekFurnitureOneRecord_pb2 as HomeSeekFurnitureOneRecord__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n HomeSeekFurnitureAllRecord.proto\x1a HomeSeekFurnitureOneRecord.proto\"M\n\x1aHomeSeekFurnitureAllRecord\x12/\n\nrecordList\x18\x05 \x03(\x0b\x32\x1b.HomeSeekFurnitureOneRecordB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeSeekFurnitureAllRecord_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HOMESEEKFURNITUREALLRECORD']._serialized_start=70
  _globals['_HOMESEEKFURNITUREALLRECORD']._serialized_end=147
# @@protoc_insertion_point(module_scope)
