# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeEditCustomFurnitureRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeCustomFurnitureInfo_pb2 as HomeCustomFurnitureInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n HomeEditCustomFurnitureRsp.proto\x1a\x1dHomeCustomFurnitureInfo.proto\"d\n\x1aHomeEditCustomFurnitureRsp\x12\x0f\n\x07retcode\x18\x07 \x01(\x05\x12\x35\n\x13\x63ustomFurnitureInfo\x18\x0b \x01(\x0b\x32\x18.HomeCustomFurnitureInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeEditCustomFurnitureRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HOMEEDITCUSTOMFURNITURERSP']._serialized_start=67
  _globals['_HOMEEDITCUSTOMFURNITURERSP']._serialized_end=167
# @@protoc_insertion_point(module_scope)
