# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeFurnitureSuiteData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cHomeFurnitureSuiteData.proto\x1a\x0cVector.proto\"\x8d\x01\n\x16HomeFurnitureSuiteData\x12\"\n\x1aincludedFurnitureIndexList\x18\x07 \x03(\x05\x12\x0c\n\x04guid\x18\x0c \x01(\r\x12\x0f\n\x07suiteId\x18\x0f \x01(\r\x12\x15\n\risAllowSummon\x18\x0e \x01(\x08\x12\x19\n\x08spawnPos\x18\n \x01(\x0b\x32\x07.VectorB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeFurnitureSuiteData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HOMEFURNITURESUITEDATA']._serialized_start=47
  _globals['_HOMEFURNITURESUITEDATA']._serialized_end=188
# @@protoc_insertion_point(module_scope)
