# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeExchangeWoodReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19HomeExchangeWoodReq.proto\"\xa7\x01\n\x13HomeExchangeWoodReq\x12\x46\n\x12material_count_map\x18\x02 \x03(\x0b\x32*.HomeExchangeWoodReq.MaterialCountMapEntry\x12\x0f\n\x07wood_id\x18\x0c \x01(\r\x1a\x37\n\x15MaterialCountMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeExchangeWoodReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _HOMEEXCHANGEWOODREQ_MATERIALCOUNTMAPENTRY._options = None
  _HOMEEXCHANGEWOODREQ_MATERIALCOUNTMAPENTRY._serialized_options = b'8\001'
  _globals['_HOMEEXCHANGEWOODREQ']._serialized_start=30
  _globals['_HOMEEXCHANGEWOODREQ']._serialized_end=197
  _globals['_HOMEEXCHANGEWOODREQ_MATERIALCOUNTMAPENTRY']._serialized_start=142
  _globals['_HOMEEXCHANGEWOODREQ_MATERIALCOUNTMAPENTRY']._serialized_end=197
# @@protoc_insertion_point(module_scope)
