# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeGetFishFarmingInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HomeFishFarmingInfo_pb2 as HomeFishFarmingInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fHomeGetFishFarmingInfoRsp.proto\x1a\x19HomeFishFarmingInfo.proto\"b\n\x19HomeGetFishFarmingInfoRsp\x12\x34\n\x16\x66ish_farming_info_list\x18\x07 \x03(\x0b\x32\x14.HomeFishFarmingInfo\x12\x0f\n\x07retcode\x18\x02 \x01(\x05\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeGetFishFarmingInfoRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_HOMEGETFISHFARMINGINFORSP']._serialized_start=62
  _globals['_HOMEGETFISHFARMINGINFORSP']._serialized_end=160
# @@protoc_insertion_point(module_scope)
