# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeAnimalData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14HomeAnimalData.proto\x1a\x0cVector.proto\"[\n\x0eHomeAnimalData\x12\x19\n\x08spawnRot\x18\r \x01(\x0b\x32\x07.Vector\x12\x13\n\x0b\x66urnitureId\x18\n \x01(\r\x12\x19\n\x08spawnPos\x18\x04 \x01(\x0b\x32\x07.VectorB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HomeAnimalData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HOMEANIMALDATA']._serialized_start=38
  _globals['_HOMEANIMALDATA']._serialized_end=129
# @@protoc_insertion_point(module_scope)
