# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HuntingSuccessNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HuntingPair_pb2 as HuntingPair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aHuntingSuccessNotify.proto\x1a\x11HuntingPair.proto\":\n\x14HuntingSuccessNotify\x12\"\n\x0chunting_pair\x18\x07 \x01(\x0b\x32\x0c.HuntingPairB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HuntingSuccessNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_HUNTINGSUCCESSNOTIFY']._serialized_start=49
  _globals['_HUNTINGSUCCESSNOTIFY']._serialized_end=107
# @@protoc_insertion_point(module_scope)
