# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InBattleMechanicusCardChallengeState.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*InBattleMechanicusCardChallengeState.proto*\xfd\x01\n$InBattleMechanicusCardChallengeState\x12\x32\n.IN_BATTLE_MECHANICUS_CARD_CHALLENGE_STATE_NONE\x10\x00\x12\x36\n2IN_BATTLE_MECHANICUS_CARD_CHALLENGE_STATE_ON_GOING\x10\x01\x12\x32\n.IN_BATTLE_MECHANICUS_CARD_CHALLENGE_STATE_FAIL\x10\x02\x12\x35\n1IN_BATTLE_MECHANICUS_CARD_CHALLENGE_STATE_SUCCESS\x10\x03\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InBattleMechanicusCardChallengeState_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_INBATTLEMECHANICUSCARDCHALLENGESTATE']._serialized_start=47
  _globals['_INBATTLEMECHANICUSCARDCHALLENGESTATE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
