# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InBattleFleurFairInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bInBattleFleurFairInfo.proto\"\x86\x01\n\x15InBattleFleurFairInfo\x12\x13\n\x0b\x65mdkpmhihmp\x18\x0b \x01(\r\x12\x19\n\x11galleryStageIndex\x18\x04 \x01(\r\x12\x13\n\x0b\x64\x65\x66\x64lkbmipk\x18\n \x03(\r\x12\x13\n\x0b\x65nokedgdhfb\x18\t \x01(\r\x12\x13\n\x0b\x66ieibhkablj\x18\x0f \x03(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InBattleFleurFairInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_INBATTLEFLEURFAIRINFO']._serialized_start=32
  _globals['_INBATTLEFLEURFAIRINFO']._serialized_end=166
# @@protoc_insertion_point(module_scope)
