# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InBattleMechanicusSettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MultistageSettleWatcherInfo_pb2 as MultistageSettleWatcherInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$InBattleMechanicusSettleNotify.proto\x1a!MultistageSettleWatcherInfo.proto\"\xf6\x01\n\x1eInBattleMechanicusSettleNotify\x12\x31\n\x0bwatcherList\x18\x07 \x03(\x0b\x32\x1c.MultistageSettleWatcherInfo\x12\x11\n\tisSuccess\x18\x08 \x01(\x08\x12\x1b\n\x13Unk3300_NAMBBHMJJLN\x18\x0f \x01(\r\x12\x1b\n\x13Unk3300_HAEOPAOBBFE\x18\x01 \x01(\r\x12\x11\n\tplayIndex\x18\x0c \x01(\r\x12\x1b\n\x13Unk3300_EKAIAPLNIPM\x18\r \x01(\r\x12\x13\n\x0bsceneTimeMs\x18\n \x01(\x04\x12\x0f\n\x07groupId\x18\t \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InBattleMechanicusSettleNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_INBATTLEMECHANICUSSETTLENOTIFY']._serialized_start=76
  _globals['_INBATTLEMECHANICUSSETTLENOTIFY']._serialized_end=322
# @@protoc_insertion_point(module_scope)
