# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: INJEGNBKGCB.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BreakoutAction_pb2 as BreakoutAction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11INJEGNBKGCB.proto\x1a\x14\x42reakoutAction.proto\"3\n\x0bINJEGNBKGCB\x12$\n\x0bNOAJNAPDEMN\x18\x0e \x01(\x0b\x32\x0f.BreakoutActionB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'INJEGNBKGCB_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_INJEGNBKGCB']._serialized_start=43
  _globals['_INJEGNBKGCB']._serialized_end=94
# @@protoc_insertion_point(module_scope)
