# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InstableSprayRestartDungeonReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import InstableSprayAvatarInfo_pb2 as InstableSprayAvatarInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$InstableSprayRestartDungeonReq.proto\x1a\x1dInstableSprayAvatarInfo.proto\"T\n\x1eInstableSprayRestartDungeonReq\x12\x32\n\x10\x61vatar_info_list\x18\x0e \x03(\x0b\x32\x18.InstableSprayAvatarInfoB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InstableSprayRestartDungeonReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_INSTABLESPRAYRESTARTDUNGEONREQ']._serialized_start=71
  _globals['_INSTABLESPRAYRESTARTDUNGEONREQ']._serialized_end=155
# @@protoc_insertion_point(module_scope)
