# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IrodoriChessMysteryInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IrodoriChessEntranceDetailInfo_pb2 as IrodoriChessEntranceDetailInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dIrodoriChessMysteryInfo.proto\x1a$IrodoriChessEntranceDetailInfo.proto\"\x94\x01\n\x17IrodoriChessMysteryInfo\x12\x1e\n\x16\x65ntrance_point_id_list\x18\x0e \x03(\r\x12=\n\x14\x65ntrance_detail_info\x18\x07 \x01(\x0b\x32\x1f.IrodoriChessEntranceDetailInfo\x12\x1a\n\x12\x65xit_point_id_list\x18\x0b \x03(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IrodoriChessMysteryInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_IRODORICHESSMYSTERYINFO']._serialized_start=72
  _globals['_IRODORICHESSMYSTERYINFO']._serialized_end=220
# @@protoc_insertion_point(module_scope)
