# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IslandPartySailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GalleryStartSource_pb2 as GalleryStartSource__pb2
import IslandPartySailStage_pb2 as IslandPartySailStage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19IslandPartySailInfo.proto\x1a\x18GalleryStartSource.proto\x1a\x1aIslandPartySailStage.proto\"\xe7\x01\n\x13IslandPartySailInfo\x12(\n\x0bstartSource\x18\x01 \x01(\x0e\x32\x13.GalleryStartSource\x12\x1b\n\x13Unk3300_MJOIIJIBAHF\x18\x05 \x01(\r\x12\x1b\n\x13Unk3300_MJHMCAPGBIK\x18\x0b \x01(\r\x12$\n\x05stage\x18\x0e \x01(\x0e\x32\x15.IslandPartySailStage\x12\x1b\n\x13Unk3300_HCJGDHEMBLM\x18\x07 \x01(\r\x12\x0c\n\x04\x63oin\x18\r \x01(\r\x12\x1b\n\x13Unk3300_PFCJODGNDCI\x18\x08 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IslandPartySailInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ISLANDPARTYSAILINFO']._serialized_start=84
  _globals['_ISLANDPARTYSAILINFO']._serialized_end=315
# @@protoc_insertion_point(module_scope)
