# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ItemGivingReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ItemGivingReq.proto\x1a\x0fItemParam.proto\"\xa5\x02\n\rItemGivingReq\x12\x41\n\x13item_guid_count_map\x18\n \x03(\x0b\x32$.ItemGivingReq.ItemGuidCountMapEntry\x12#\n\x0fitem_param_list\x18\x0f \x03(\x0b\x32\n.ItemParam\x12\x37\n\x10item_giving_type\x18\x01 \x01(\x0e\x32\x1d.ItemGivingReq.ItemGivingType\x12\x11\n\tgiving_id\x18\x02 \x01(\r\x1a\x37\n\x15ItemGuidCountMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"\'\n\x0eItemGivingType\x12\t\n\x05QUEST\x10\x00\x12\n\n\x06GADGET\x10\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ItemGivingReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _ITEMGIVINGREQ_ITEMGUIDCOUNTMAPENTRY._options = None
  _ITEMGIVINGREQ_ITEMGUIDCOUNTMAPENTRY._serialized_options = b'8\001'
  _globals['_ITEMGIVINGREQ']._serialized_start=41
  _globals['_ITEMGIVINGREQ']._serialized_end=334
  _globals['_ITEMGIVINGREQ_ITEMGUIDCOUNTMAPENTRY']._serialized_start=238
  _globals['_ITEMGIVINGREQ_ITEMGUIDCOUNTMAPENTRY']._serialized_end=293
  _globals['_ITEMGIVINGREQ_ITEMGIVINGTYPE']._serialized_start=295
  _globals['_ITEMGIVINGREQ_ITEMGIVINGTYPE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
