# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JGMCLGAMEOA.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11JGMCLGAMEOA.proto\"\xf5\x01\n\x0bJGMCLGAMEOA\x12(\n\x06reason\x18\x06 \x01(\x0e\x32\x18.JGMCLGAMEOA.AIFELBCMNGE\"\xbb\x01\n\x0b\x41IFELBCMNGE\x12\x1b\n\x17\x41IFELBCMNGE_NONDINLCGFO\x10\x00\x12\x1b\n\x17\x41IFELBCMNGE_CGAFAKMGIBO\x10\x01\x12\x1b\n\x17\x41IFELBCMNGE_NINOFNAFKHO\x10\x02\x12\x1b\n\x17\x41IFELBCMNGE_GOIPCFPLOLG\x10\x03\x12\x1b\n\x17\x41IFELBCMNGE_JJNMPNGFHOI\x10\x04\x12\x1b\n\x17\x41IFELBCMNGE_MEPDCLLKNPN\x10\x05\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'JGMCLGAMEOA_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_JGMCLGAMEOA']._serialized_start=22
  _globals['_JGMCLGAMEOA']._serialized_end=267
  _globals['_JGMCLGAMEOA_AIFELBCMNGE']._serialized_start=80
  _globals['_JGMCLGAMEOA_AIFELBCMNGE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
