# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JIJOIEGIHPM.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ADLNAMCMMNP_pb2 as ADLNAMCMMNP__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11JIJOIEGIHPM.proto\x1a\x11\x41\x44LNAMCMMNP.proto\"0\n\x0bJIJOIEGIHPM\x12!\n\x0bIDIDBDBCJKK\x18\x01 \x03(\x0b\x32\x0c.ADLNAMCMMNPB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'JIJOIEGIHPM_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_JIJOIEGIHPM']._serialized_start=40
  _globals['_JIJOIEGIHPM']._serialized_end=88
# @@protoc_insertion_point(module_scope)
