# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JNONGGFHNMC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import KIMICJIEGDD_pb2 as KIMICJIEGDD__pb2
import NHIJPCNBKJE_pb2 as NHIJPCNBKJE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11JNONGGFHNMC.proto\x1a\x11KIMICJIEGDD.proto\x1a\x11NHIJPCNBKJE.proto\"\xb5\x01\n\x0bJNONGGFHNMC\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x46\x45\x44IANCDPPE\x18\x02 \x01(\t\x12\x13\n\x0bNNODEKCPMPJ\x18\x03 \x01(\x08\x12\x13\n\x0bLFFPKIEJOLH\x18\x04 \x01(\t\x12\x13\n\x0b\x44MOGKFBJKLC\x18\x05 \x01(\x08\x12!\n\x0bPNFIHGPGNKD\x18\x06 \x03(\x0b\x32\x0c.NHIJPCNBKJE\x12!\n\x0b\x46\x46\x44\x41HCPMGAI\x18\x07 \x01(\x0e\x32\x0c.KIMICJIEGDDB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'JNONGGFHNMC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_JNONGGFHNMC']._serialized_start=60
  _globals['_JNONGGFHNMC']._serialized_end=241
# @@protoc_insertion_point(module_scope)
