# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JONHAPLJANI.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11JONHAPLJANI.proto\"c\n\x0bJONHAPLJANI\x12\x11\n\tis_finish\x18\x0c \x01(\x08\x12\x17\n\x0fmin_finish_time\x18\x04 \x01(\r\x12\x13\n\x0bLEDKDCJIDNE\x18\x05 \x01(\r\x12\x13\n\x0bis_have_try\x18\x08 \x01(\x08\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'JONHAPLJANI_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_JONHAPLJANI']._serialized_start=21
  _globals['_JONHAPLJANI']._serialized_end=120
# @@protoc_insertion_point(module_scope)
