# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LanternRiteEndFireworksReformRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&LanternRiteEndFireworksReformRsp.proto\"\xee\x01\n LanternRiteEndFireworksReformRsp\x12\x12\n\nfinalScore\x18\x08 \x01(\r\x12\x13\n\x0b\x63hallengeId\x18\n \x01(\r\x12\x0f\n\x07stageId\x18\t \x01(\r\x12\x1b\n\x13Unk3300_ALMNEGCIILA\x18\x06 \x01(\x08\x12\x13\n\x0bisFullScore\x18\x04 \x01(\x08\x12\x0f\n\x07retcode\x18\r \x01(\x05\x12\x1b\n\x13Unk3300_FPEFIADFBNI\x18\x07 \x01(\x08\x12\x1b\n\x13Unk3300_CGJNBGAKFAD\x18\x0b \x01(\x08\x12\x13\n\x0bisNewRecord\x18\x0c \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LanternRiteEndFireworksReformRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_LANTERNRITEENDFIREWORKSREFORMRSP']._serialized_start=43
  _globals['_LANTERNRITEENDFIREWORKSREFORMRSP']._serialized_end=281
# @@protoc_insertion_point(module_scope)
