# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MapMarkPointType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16MapMarkPointType.proto*i\n\x10MapMarkPointType\x12\x07\n\x03NPC\x10\x00\x12\t\n\x05QUEST\x10\x01\x12\x0b\n\x07SPECIAL\x10\x02\x12\x08\n\x04MINE\x10\x03\x12\x0e\n\nCOLLECTION\x10\x04\x12\x0b\n\x07MONSTER\x10\x05\x12\r\n\tFISH_POOL\x10\x06\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MapMarkPointType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_MAPMARKPOINTTYPE']._serialized_start=26
  _globals['_MAPMARKPOINTTYPE']._serialized_end=131
# @@protoc_insertion_point(module_scope)
