# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MistTrialSettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MistTrialBestAvatar_pb2 as MistTrialBestAvatar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bMistTrialSettleNotify.proto\x1a\x19MistTrialBestAvatar.proto\"\x8d\x03\n\x15MistTrialSettleNotify\x12.\n\x10\x62\x65st_avatar_list\x18\x03 \x03(\x0b\x32\x14.MistTrialBestAvatar\x12\x17\n\x0f\x66irst_pass_time\x18\x08 \x01(\r\x12<\n\x0bIIGOLKJOKAL\x18\x0f \x03(\x0b\x32\'.MistTrialSettleNotify.IIGOLKJOKALEntry\x12-\n\x0f\x62\x65st_hit_avatar\x18\x05 \x01(\x0b\x32\x14.MistTrialBestAvatar\x12<\n\x0bGIGIAGDALHG\x18\x0c \x03(\x0b\x32\'.MistTrialSettleNotify.GIGIAGDALHGEntry\x12\x18\n\x10\x64ungeon_scene_id\x18\x0e \x01(\r\x1a\x32\n\x10IIGOLKJOKALEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x32\n\x10GIGIAGDALHGEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MistTrialSettleNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _MISTTRIALSETTLENOTIFY_IIGOLKJOKALENTRY._options = None
  _MISTTRIALSETTLENOTIFY_IIGOLKJOKALENTRY._serialized_options = b'8\001'
  _MISTTRIALSETTLENOTIFY_GIGIAGDALHGENTRY._options = None
  _MISTTRIALSETTLENOTIFY_GIGIAGDALHGENTRY._serialized_options = b'8\001'
  _globals['_MISTTRIALSETTLENOTIFY']._serialized_start=59
  _globals['_MISTTRIALSETTLENOTIFY']._serialized_end=456
  _globals['_MISTTRIALSETTLENOTIFY_IIGOLKJOKALENTRY']._serialized_start=354
  _globals['_MISTTRIALSETTLENOTIFY_IIGOLKJOKALENTRY']._serialized_end=404
  _globals['_MISTTRIALSETTLENOTIFY_GIGIAGDALHGENTRY']._serialized_start=406
  _globals['_MISTTRIALSETTLENOTIFY_GIGIAGDALHGENTRY']._serialized_end=456
# @@protoc_insertion_point(module_scope)
