# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MNFJFJANFEH.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11MNFJFJANFEH.proto\"L\n\x0bMNFJFJANFEH\x12\x12\n\nbest_score\x18\r \x01(\r\x12\x13\n\x0bKHCOGGPJNML\x18\x0f \x01(\x08\x12\x14\n\x0c\x63hallenge_id\x18\x0b \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MNFJFJANFEH_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_MNFJFJANFEH']._serialized_start=21
  _globals['_MNFJFJANFEH']._serialized_end=97
# @@protoc_insertion_point(module_scope)
