# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MODKOILPBDN.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LHIBCFCHIHG_pb2 as LHIBCFCHIHG__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11MODKOILPBDN.proto\x1a\x11LHIBCFCHIHG.proto\".\n\x0bMODKOILPBDN\x12\x1f\n\tbriefList\x18\x01 \x03(\x0b\x32\x0c.LHIBCFCHIHGB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MODKOILPBDN_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_MODKOILPBDN']._serialized_start=40
  _globals['_MODKOILPBDN']._serialized_end=86
# @@protoc_insertion_point(module_scope)
