# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MpPlayGuestReplyInviteReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fMpPlayGuestReplyInviteReq.proto\">\n\x19MpPlayGuestReplyInviteReq\x12\x10\n\x08mpPlayId\x18\x06 \x01(\r\x12\x0f\n\x07isAgree\x18\x07 \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MpPlayGuestReplyInviteReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_MPPLAYGUESTREPLYINVITEREQ']._serialized_start=35
  _globals['_MPPLAYGUESTREPLYINVITEREQ']._serialized_end=97
# @@protoc_insertion_point(module_scope)
