# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MpPlayOwnerStartInviteReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fMpPlayOwnerStartInviteReq.proto\"B\n\x19MpPlayOwnerStartInviteReq\x12\x13\n\x0bisSkipMatch\x18\r \x01(\x08\x12\x10\n\x08mpPlayId\x18\n \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MpPlayOwnerStartInviteReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_MPPLAYOWNERSTARTINVITEREQ']._serialized_start=35
  _globals['_MPPLAYOWNERSTARTINVITEREQ']._serialized_end=101
# @@protoc_insertion_point(module_scope)
