# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MusicBriefInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MusicBriefInfo.proto\"\x9d\x04\n\x0eMusicBriefInfo\x12\x0f\n\x07ugcGuid\x18\x08 \x01(\x04\x12\x1b\n\x13Unk3300_CCMMPAHIMDO\x18X \x01(\r\x12\x1b\n\x13Unk3300_PLNOFOHFAPE\x18\x0f \x01(\r\x12\x1c\n\x13Unk3300_HKBHAIMOBKO\x18\xd3\n \x03(\r\x12\x1b\n\x13Unk3300_FKIGPAJFPLG\x18\x05 \x01(\x08\x12\x19\n\x11importFromUgcGuid\x18\x06 \x01(\x04\x12\x0f\n\x07musicId\x18\x0e \x01(\r\x12\x1c\n\x13Unk3300_JEEBFPFEHHG\x18\xa6\x08 \x03(\r\x12\x1c\n\x13Unk3300_MBKDGBNFPOA\x18\xad\x0e \x01(\r\x12\x1b\n\x13Unk3300_OJOKFBJALIJ\x18\x07 \x01(\r\x12\x1c\n\x13Unk3300_EGIGIOOKBAB\x18\x9f\x02 \x01(\r\x12\x1b\n\x13Unk3300_OBBMCFADNIN\x18\x02 \x01(\r\x12\x1b\n\x13Unk3300_PBENMAHHGIL\x18\t \x01(\r\x12\x1b\n\x13Unk3300_NCDKCNOLGKB\x18\x04 \x01(\x08\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x17\n\x0f\x63reatorNickname\x18\x03 \x01(\t\x12\x1b\n\x13Unk3300_GDNAPNAINBA\x18\x0b \x01(\x08\x12\x10\n\x08maxScore\x18\x0c \x01(\r\x12\x1b\n\x13Unk3300_KMMBLIMKJCM\x18\n \x01(\r\x12\x15\n\risPsnPlatform\x18\r \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MusicBriefInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_MUSICBRIEFINFO']._serialized_start=25
  _globals['_MUSICBRIEFINFO']._serialized_end=566
# @@protoc_insertion_point(module_scope)
