# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MusicGameSettleRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18MusicGameSettleRsp.proto\"|\n\x12MusicGameSettleRsp\x12\x0f\n\x07retcode\x18\t \x01(\x05\x12\x19\n\x11isUnlockNextLevel\x18\x01 \x01(\x08\x12\x0f\n\x07ugcGuid\x18\x07 \x01(\x04\x12\x14\n\x0cmusicBasicId\x18\x04 \x01(\r\x12\x13\n\x0bisNewRecord\x18\x0e \x01(\x08\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MusicGameSettleRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_MUSICGAMESETTLERSP']._serialized_start=28
  _globals['_MUSICGAMESETTLERSP']._serialized_end=152
# @@protoc_insertion_point(module_scope)
