# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MusicGameActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MusicBriefInfo_pb2 as MusicBriefInfo__pb2
import MusicGameRecord_pb2 as MusicGameRecord__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!MusicGameActivityDetailInfo.proto\x1a\x14MusicBriefInfo.proto\x1a\x15MusicGameRecord.proto\"\x98\x02\n\x1bMusicGameActivityDetailInfo\x12,\n\x13Unk3300_AAGCDCOIPJM\x18\x02 \x03(\x0b\x32\x0f.MusicBriefInfo\x12,\n\x13Unk3300_OKHAACGHMAP\x18\x06 \x03(\x0b\x32\x0f.MusicBriefInfo\x12P\n\x12musicGameRecordMap\x18\x08 \x03(\x0b\x32\x34.MusicGameActivityDetailInfo.MusicGameRecordMapEntry\x1aK\n\x17MusicGameRecordMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.MusicGameRecord:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MusicGameActivityDetailInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _MUSICGAMEACTIVITYDETAILINFO_MUSICGAMERECORDMAPENTRY._options = None
  _MUSICGAMEACTIVITYDETAILINFO_MUSICGAMERECORDMAPENTRY._serialized_options = b'8\001'
  _globals['_MUSICGAMEACTIVITYDETAILINFO']._serialized_start=83
  _globals['_MUSICGAMEACTIVITYDETAILINFO']._serialized_end=363
  _globals['_MUSICGAMEACTIVITYDETAILINFO_MUSICGAMERECORDMAPENTRY']._serialized_start=288
  _globals['_MUSICGAMEACTIVITYDETAILINFO_MUSICGAMERECORDMAPENTRY']._serialized_end=363
# @@protoc_insertion_point(module_scope)
