# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NFHMNCKJOEI.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GGBMIADMOHH_pb2 as GGBMIADMOHH__pb2
import IMADEKGFIFA_pb2 as IMADEKGFIFA__pb2
import PDHJBMOMMGJ_pb2 as PDHJBMOMMGJ__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11NFHMNCKJOEI.proto\x1a\x11GGBMIADMOHH.proto\x1a\x11IMADEKGFIFA.proto\x1a\x11PDHJBMOMMGJ.proto\"y\n\x0bNFHMNCKJOEI\x12%\n\x0fmusic_game_info\x18\x0b \x01(\x0b\x32\x0c.PDHJBMOMMGJ\x12 \n\nphoto_info\x18\r \x01(\x0b\x32\x0c.IMADEKGFIFA\x12!\n\x0bpacman_info\x18\x06 \x01(\x0b\x32\x0c.GGBMIADMOHHB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NFHMNCKJOEI_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_NFHMNCKJOEI']._serialized_start=78
  _globals['_NFHMNCKJOEI']._serialized_end=199
# @@protoc_insertion_point(module_scope)
