# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NormalUidOpNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17NormalUidOpNotify.proto\"f\n\x11NormalUidOpNotify\x12\x10\n\x08\x64uration\x18\x07 \x01(\r\x12\x12\n\nparam_list\x18\r \x03(\r\x12\x13\n\x0bparam_index\x18\x0b \x01(\r\x12\x16\n\x0eparam_uid_list\x18\x0e \x03(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NormalUidOpNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_NORMALUIDOPNOTIFY']._serialized_start=27
  _globals['_NORMALUIDOPNOTIFY']._serialized_end=129
# @@protoc_insertion_point(module_scope)
