# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenBlossomCircleCampGuideNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&OpenBlossomCircleCampGuideNotify.proto\"O\n OpenBlossomCircleCampGuideNotify\x12\x18\n\x10\x63ircleCampIdList\x18\r \x03(\r\x12\x11\n\trefreshId\x18\x05 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OpenBlossomCircleCampGuideNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_OPENBLOSSOMCIRCLECAMPGUIDENOTIFY']._serialized_start=42
  _globals['_OPENBLOSSOMCIRCLECAMPGUIDENOTIFY']._serialized_end=121
# @@protoc_insertion_point(module_scope)
