# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBCGIPFKDBD.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DKCAEHHPAGD_pb2 as DKCAEHHPAGD__pb2
import MMJFCJAIBBG_pb2 as MMJFCJAIBBG__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PBCGIPFKDBD.proto\x1a\x11\x44KCAEHHPAGD.proto\x1a\x11MMJFCJAIBBG.proto\"\xbf\x01\n\x0bPBCGIPFKDBD\x12\x13\n\x0boiibnieamib\x18\x01 \x01(\t\x12\x10\n\x08\x65ntityId\x18\x02 \x01(\t\x12\x0c\n\x04lang\x18\x03 \x01(\t\x12\x13\n\x0bkhjppnapjib\x18\x04 \x01(\t\x12\x13\n\x0b\x66\x65\x63oacjadfm\x18\x05 \x01(\t\x12\x0b\n\x03uid\x18\x06 \x01(\r\x12!\n\x0b\x66\x63jijbicndj\x18\x07 \x03(\x0b\x32\x0c.DKCAEHHPAGD\x12!\n\x0bpmbjacpclfc\x18\x08 \x03(\x0b\x32\x0c.MMJFCJAIBBGB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PBCGIPFKDBD_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_PBCGIPFKDBD']._serialized_start=60
  _globals['_PBCGIPFKDBD']._serialized_end=251
# @@protoc_insertion_point(module_scope)
