# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBNavMeshPoly.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EdgeType_pb2 as EdgeType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13PBNavMeshPoly.proto\x1a\x0e\x45\x64geType.proto\"J\n\rPBNavMeshPoly\x12\x1c\n\tedgeTypes\x18\x01 \x03(\x0e\x32\t.EdgeType\x12\x0c\n\x04\x61rea\x18\x05 \x01(\x05\x12\r\n\x05vects\x18\x0e \x03(\x05\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PBNavMeshPoly_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_PBNAVMESHPOLY']._serialized_start=39
  _globals['_PBNAVMESHPOLY']._serialized_end=113
# @@protoc_insertion_point(module_scope)
