# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbNavMeshStatsInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18PbNavMeshStatsInfo.proto\"\x88\x01\n\x12PbNavMeshStatsInfo\x12\x1b\n\x13Unk3300_DHJKKJLKDHB\x18\x01 \x01(\x05\x12\x1b\n\x13Unk3300_EEONKADBJME\x18\x0b \x01(\x05\x12\x1b\n\x13Unk3300_IMLHLJAOBLF\x18\x0c \x01(\x05\x12\x1b\n\x13Unk3300_MOKPJBIPHNI\x18\x02 \x01(\x05\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PbNavMeshStatsInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_PBNAVMESHSTATSINFO']._serialized_start=29
  _globals['_PBNAVMESHSTATSINFO']._serialized_end=165
# @@protoc_insertion_point(module_scope)
