# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PCCGJPEIAOE.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DNEFMCCIFDH_pb2 as DNEFMCCIFDH__pb2
import NMPKCMGANGK_pb2 as NMPKCMGANGK__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PCCGJPEIAOE.proto\x1a\x11\x44NEFMCCIFDH.proto\x1a\x11NMPKCMGANGK.proto\"g\n\x0bPCCGJPEIAOE\x12\x12\n\ncreateTime\x18\x01 \x01(\t\x12!\n\x0bingcalgldlb\x18\x02 \x03(\x0b\x32\x0c.NMPKCMGANGK\x12!\n\x0bjkfdibhoggm\x18\x03 \x01(\x0b\x32\x0c.DNEFMCCIFDHB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PCCGJPEIAOE_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_PCCGJPEIAOE']._serialized_start=59
  _globals['_PCCGJPEIAOE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
