# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PDHJBMOMMGJ.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MusicGameRecord_pb2 as MusicGameRecord__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PDHJBMOMMGJ.proto\x1a\x15MusicGameRecord.proto\"\x9f\x01\n\x0bPDHJBMOMMGJ\x12\x43\n\x15music_game_record_map\x18\x0b \x03(\x0b\x32$.PDHJBMOMMGJ.MusicGameRecordMapEntry\x1aK\n\x17MusicGameRecordMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.MusicGameRecord:\x02\x38\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PDHJBMOMMGJ_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _PDHJBMOMMGJ_MUSICGAMERECORDMAPENTRY._options = None
  _PDHJBMOMMGJ_MUSICGAMERECORDMAPENTRY._serialized_options = b'8\001'
  _globals['_PDHJBMOMMGJ']._serialized_start=45
  _globals['_PDHJBMOMMGJ']._serialized_end=204
  _globals['_PDHJBMOMMGJ_MUSICGAMERECORDMAPENTRY']._serialized_start=129
  _globals['_PDHJBMOMMGJ_MUSICGAMERECORDMAPENTRY']._serialized_end=204
# @@protoc_insertion_point(module_scope)
