# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PhaseChange.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGPhaseType_pb2 as GCGPhaseType__pb2
import Uint32Pair_pb2 as Uint32Pair__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PhaseChange.proto\x1a\x12GCGPhaseType.proto\x1a\x10Uint32Pair.proto\"}\n\x0bPhaseChange\x12\'\n\x12\x61llowControllerMap\x18\x07 \x03(\x0b\x32\x0b.Uint32Pair\x12!\n\nafterPhase\x18\r \x01(\x0e\x32\r.GCGPhaseType\x12\"\n\x0b\x62\x65\x66orePhase\x18\x08 \x01(\x0e\x32\r.GCGPhaseTypeB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PhaseChange_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_PHASECHANGE']._serialized_start=59
  _globals['_PHASECHANGE']._serialized_end=184
# @@protoc_insertion_point(module_scope)
