# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PIPLLHAJHGC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AJCFJJFJJMB_pb2 as AJCFJJFJJMB__pb2
import KOFKLFNBDNA_pb2 as KOFKLFNBDNA__pb2
import LJFMLGDFELG_pb2 as LJFMLGDFELG__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PIPLLHAJHGC.proto\x1a\x11\x41JCFJJFJJMB.proto\x1a\x11KOFKLFNBDNA.proto\x1a\x11LJFMLGDFELG.proto\"\xa2\x01\n\x0bPIPLLHAJHGC\x12!\n\x0bPDFBKOLMBCC\x18\x01 \x03(\x0b\x32\x0c.LJFMLGDFELG\x12\x13\n\x0b\x46\x42PBFBJEHCI\x18\x02 \x01(\r\x12!\n\x0bOKMPNOPIEAP\x18\x0f \x03(\x0b\x32\x0c.KOFKLFNBDNA\x12!\n\x0bGPFBBLIJPDG\x18\x05 \x03(\x0b\x32\x0c.AJCFJJFJJMB\x12\x15\n\rcontroller_id\x18\x08 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PIPLLHAJHGC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_PIPLLHAJHGC']._serialized_start=79
  _globals['_PIPLLHAJHGC']._serialized_end=241
# @@protoc_insertion_point(module_scope)
