# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlantFlowerGetCanGiveFriendFlowerRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*PlantFlowerGetCanGiveFriendFlowerRsp.proto\"\xcf\x01\n$PlantFlowerGetCanGiveFriendFlowerRsp\x12\x12\n\nscheduleId\x18\r \x01(\r\x12M\n\x0c\x66lowerNumMap\x18\n \x03(\x0b\x32\x37.PlantFlowerGetCanGiveFriendFlowerRsp.FlowerNumMapEntry\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x1a\x33\n\x11\x46lowerNumMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlantFlowerGetCanGiveFriendFlowerRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _PLANTFLOWERGETCANGIVEFRIENDFLOWERRSP_FLOWERNUMMAPENTRY._options = None
  _PLANTFLOWERGETCANGIVEFRIENDFLOWERRSP_FLOWERNUMMAPENTRY._serialized_options = b'8\001'
  _globals['_PLANTFLOWERGETCANGIVEFRIENDFLOWERRSP']._serialized_start=47
  _globals['_PLANTFLOWERGETCANGIVEFRIENDFLOWERRSP']._serialized_end=254
  _globals['_PLANTFLOWERGETCANGIVEFRIENDFLOWERRSP_FLOWERNUMMAPENTRY']._serialized_start=203
  _globals['_PLANTFLOWERGETCANGIVEFRIENDFLOWERRSP_FLOWERNUMMAPENTRY']._serialized_end=254
# @@protoc_insertion_point(module_scope)
