# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlantFlowerAcceptGiveFlowerRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PlantFlowerAcceptFlowerResultInfo_pb2 as PlantFlowerAcceptFlowerResultInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$PlantFlowerAcceptGiveFlowerRsp.proto\x1a\'PlantFlowerAcceptFlowerResultInfo.proto\"\x89\x01\n\x1ePlantFlowerAcceptGiveFlowerRsp\x12\x12\n\nscheduleId\x18\x04 \x01(\r\x12\x0f\n\x07retcode\x18\x0c \x01(\x05\x12\x42\n\x16\x61\x63\x63\x65ptFlowerResultInfo\x18\x0e \x01(\x0b\x32\".PlantFlowerAcceptFlowerResultInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlantFlowerAcceptGiveFlowerRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_PLANTFLOWERACCEPTGIVEFLOWERRSP']._serialized_start=82
  _globals['_PLANTFLOWERACCEPTGIVEFLOWERRSP']._serialized_end=219
# @@protoc_insertion_point(module_scope)
