# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerPropChangeReasonNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PropChangeReason_pb2 as PropChangeReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"PlayerPropChangeReasonNotify.proto\x1a\x16PropChangeReason.proto\"w\n\x1cPlayerPropChangeReasonNotify\x12\x10\n\x08propType\x18\x06 \x01(\r\x12\x10\n\x08oldValue\x18\x0c \x01(\x02\x12\x10\n\x08\x63urValue\x18\t \x01(\x02\x12!\n\x06reason\x18\x01 \x01(\x0e\x32\x11.PropChangeReasonB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerPropChangeReasonNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_PLAYERPROPCHANGEREASONNOTIFY']._serialized_start=62
  _globals['_PLAYERPROPCHANGEREASONNOTIFY']._serialized_end=181
# @@protoc_insertion_point(module_scope)
