# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayTeamEntityInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AbilitySyncStateInfo_pb2 as AbilitySyncStateInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18PlayTeamEntityInfo.proto\x1a\x1a\x41\x62ilitySyncStateInfo.proto\"\x9d\x01\n\x12PlayTeamEntityInfo\x12\x11\n\tentity_id\x18\x01 \x01(\r\x12\x12\n\nplayer_uid\x18\x02 \x01(\r\x12\x19\n\x11\x61uthority_peer_id\x18\x03 \x01(\r\x12\x18\n\x10gadget_config_id\x18\x05 \x01(\r\x12+\n\x0c\x61\x62ility_info\x18\x06 \x01(\x0b\x32\x15.AbilitySyncStateInfoB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayTeamEntityInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_PLAYTEAMENTITYINFO']._serialized_start=57
  _globals['_PLAYTEAMENTITYINFO']._serialized_end=214
# @@protoc_insertion_point(module_scope)
