# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerGCGMatchConfirmNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!PlayerGCGMatchConfirmNotify.proto\"N\n\x1bPlayerGCGMatchConfirmNotify\x12\x0b\n\x03uid\x18\x07 \x01(\r\x12\x10\n\x08is_agree\x18\x08 \x01(\x08\x12\x10\n\x08match_id\x18\x01 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerGCGMatchConfirmNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_PLAYERGCGMATCHCONFIRMNOTIFY']._serialized_start=37
  _globals['_PLAYERGCGMATCHCONFIRMNOTIFY']._serialized_end=115
# @@protoc_insertion_point(module_scope)
