# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerWidgetInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WidgetSlotData_pb2 as WidgetSlotData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16PlayerWidgetInfo.proto\x1a\x14WidgetSlotData.proto\"C\n\x10PlayerWidgetInfo\x12\x0b\n\x03uid\x18\x04 \x01(\r\x12\"\n\tslot_list\x18\t \x03(\x0b\x32\x0f.WidgetSlotDataB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerWidgetInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_PLAYERWIDGETINFO']._serialized_start=48
  _globals['_PLAYERWIDGETINFO']._serialized_end=115
# @@protoc_insertion_point(module_scope)
