# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerMatchInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MatchType_pb2 as MatchType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bPlayerMatchInfoNotify.proto\x1a\x0fMatchType.proto\"\xeb\x01\n\x15PlayerMatchInfoNotify\x12\x12\n\ndungeon_id\x18\x05 \x01(\r\x12\x10\n\x08host_uid\x18\t \x01(\r\x12\x18\n\x10match_param_list\x18\x0b \x03(\r\x12\x13\n\x0b\x42\x42PAKLDFKOH\x18\x0e \x01(\r\x12\x1e\n\nmatch_type\x18\x03 \x01(\x0e\x32\n.MatchType\x12\x12\n\nmp_play_id\x18\n \x01(\r\x12\x10\n\x08match_id\x18\x07 \x01(\r\x12\x13\n\x0bLLBEFAFNBON\x18\r \x01(\r\x12\"\n\x1amechanicus_difficult_level\x18\x0f \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerMatchInfoNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_PLAYERMATCHINFONOTIFY']._serialized_start=49
  _globals['_PLAYERMATCHINFONOTIFY']._serialized_end=284
# @@protoc_insertion_point(module_scope)
