# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerCookRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CookRecipeData_pb2 as CookRecipeData__pb2
import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13PlayerCookRsp.proto\x1a\x14\x43ookRecipeData.proto\x1a\x0fItemParam.proto\"\xad\x01\n\rPlayerCookRsp\x12\x0f\n\x07retcode\x18\x07 \x01(\x05\x12!\n\rextraItemList\x18\r \x03(\x0b\x32\n.ItemParam\x12\x1c\n\x08itemList\x18\t \x03(\x0b\x32\n.ItemParam\x12#\n\nrecipeData\x18\x05 \x01(\x0b\x32\x0f.CookRecipeData\x12\x11\n\tcookCount\x18\x0c \x01(\r\x12\x12\n\nqteQuality\x18\x04 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerCookRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_PLAYERCOOKRSP']._serialized_start=63
  _globals['_PLAYERCOOKRSP']._serialized_end=236
# @@protoc_insertion_point(module_scope)
