# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerChatReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatInfo_pb2 as ChatInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13PlayerChatReq.proto\x1a\x0e\x43hatInfo.proto\"A\n\rPlayerChatReq\x12\x1c\n\tchat_info\x18\x05 \x01(\x0b\x32\t.ChatInfo\x12\x12\n\nchannel_id\x18\x0f \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerChatReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_PLAYERCHATREQ']._serialized_start=39
  _globals['_PLAYERCHATREQ']._serialized_end=104
# @@protoc_insertion_point(module_scope)
