# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PropValue.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fPropValue.proto\"O\n\tPropValue\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0b\n\x03val\x18\x04 \x01(\x03\x12\x0e\n\x04ival\x18\x02 \x01(\x03H\x00\x12\x0e\n\x04\x66val\x18\x03 \x01(\x02H\x00\x42\x07\n\x05valueB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PropValue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_PROPVALUE']._serialized_start=19
  _globals['_PROPVALUE']._serialized_end=98
# @@protoc_insertion_point(module_scope)
