# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProudSkillExtraLevelNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ProudSkillExtraLevelNotify.proto\"m\n\x1aProudSkillExtraLevelNotify\x12\x13\n\x0btalentIndex\x18\x04 \x01(\r\x12\x12\n\navatarGuid\x18\x02 \x01(\x04\x12\x12\n\ntalentType\x18\x05 \x01(\r\x12\x12\n\nextraLevel\x18\r \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProudSkillExtraLevelNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_PROUDSKILLEXTRALEVELNOTIFY']._serialized_start=36
  _globals['_PROUDSKILLEXTRALEVELNOTIFY']._serialized_end=145
# @@protoc_insertion_point(module_scope)
