# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullPrivateChatRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatInfo_pb2 as ChatInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18PullPrivateChatRsp.proto\x1a\x0e\x43hatInfo.proto\"C\n\x12PullPrivateChatRsp\x12\x0f\n\x07retcode\x18\n \x01(\x05\x12\x1c\n\tchat_info\x18\x0f \x03(\x0b\x32\t.ChatInfoB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PullPrivateChatRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_PULLPRIVATECHATRSP']._serialized_start=44
  _globals['_PULLPRIVATECHATRSP']._serialized_end=111
# @@protoc_insertion_point(module_scope)
