# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PveIntentionInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGMsgPVEIntention_pb2 as GCGMsgPVEIntention__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16PveIntentionInfo.proto\x1a\x18GCGMsgPVEIntention.proto\"\x97\x01\n\x10PveIntentionInfo\x12\x39\n\x0cintentionMap\x18\x0f \x03(\x0b\x32#.PveIntentionInfo.IntentionMapEntry\x1aH\n\x11IntentionMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.GCGMsgPVEIntention:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PveIntentionInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _PVEINTENTIONINFO_INTENTIONMAPENTRY._options = None
  _PVEINTENTIONINFO_INTENTIONMAPENTRY._serialized_options = b'8\001'
  _globals['_PVEINTENTIONINFO']._serialized_start=53
  _globals['_PVEINTENTIONINFO']._serialized_end=204
  _globals['_PVEINTENTIONINFO_INTENTIONMAPENTRY']._serialized_start=132
  _globals['_PVEINTENTIONINFO_INTENTIONMAPENTRY']._serialized_end=204
# @@protoc_insertion_point(module_scope)
