# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReliquaryUpgradeReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ReliquaryUpgradeReq.proto\x1a\x0fItemParam.proto\"{\n\x13ReliquaryUpgradeReq\x12 \n\x18\x66ood_reliquary_guid_list\x18\x0e \x03(\x04\x12#\n\x0fitem_param_list\x18\x0f \x03(\x0b\x32\n.ItemParam\x12\x1d\n\x15target_reliquary_guid\x18\x0c \x01(\x04\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReliquaryUpgradeReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_RELIQUARYUPGRADEREQ']._serialized_start=46
  _globals['_RELIQUARYUPGRADEREQ']._serialized_end=169
# @@protoc_insertion_point(module_scope)
