# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemoveRandTaskInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eRemoveRandTaskInfoNotify.proto\"\xbb\x01\n\x18RemoveRandTaskInfoNotify\x12\x36\n\x06reason\x18\r \x01(\x0e\x32&.RemoveRandTaskInfoNotify.FinishReason\x12\x14\n\x0crand_task_id\x18\x05 \x01(\r\x12\x0f\n\x07is_succ\x18\t \x01(\x08\"@\n\x0c\x46inishReason\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05\x43LEAR\x10\x01\x12\x0c\n\x08\x44ISTANCE\x10\x02\x12\n\n\x06\x46INISH\x10\x03\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RemoveRandTaskInfoNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_REMOVERANDTASKINFONOTIFY']._serialized_start=35
  _globals['_REMOVERANDTASKINFONOTIFY']._serialized_end=222
  _globals['_REMOVERANDTASKINFONOTIFY_FINISHREASON']._serialized_start=158
  _globals['_REMOVERANDTASKINFONOTIFY_FINISHREASON']._serialized_end=222
# @@protoc_insertion_point(module_scope)
