# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemotePlayerWidgetNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PlayerWidgetInfo_pb2 as PlayerWidgetInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eRemotePlayerWidgetNotify.proto\x1a\x16PlayerWidgetInfo.proto\"N\n\x18RemotePlayerWidgetNotify\x12\x32\n\x17player_widget_info_list\x18\x04 \x03(\x0b\x32\x11.PlayerWidgetInfoB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RemotePlayerWidgetNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_REMOTEPLAYERWIDGETNOTIFY']._serialized_start=58
  _globals['_REMOTEPLAYERWIDGETNOTIFY']._serialized_end=136
# @@protoc_insertion_point(module_scope)
