# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResinCardData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ResinCardData.proto\"l\n\rResinCardData\x12\x10\n\x08\x63onfigId\x18\x0e \x01(\r\x12\x18\n\x10remainRewardDays\x18\n \x01(\r\x12\x12\n\nexpireTime\x18\x05 \x01(\r\x12\x1b\n\x13lastDailyRewardTime\x18\x07 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ResinCardData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_RESINCARDDATA']._serialized_start=23
  _globals['_RESINCARDDATA']._serialized_end=131
# @@protoc_insertion_point(module_scope)
