# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReunionPrivilegeChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ReunionPrivilegeInfo_pb2 as ReunionPrivilegeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ReunionPrivilegeChangeNotify.proto\x1a\x1aReunionPrivilegeInfo.proto\"L\n\x1cReunionPrivilegeChangeNotify\x12,\n\rprivilegeInfo\x18\r \x01(\x0b\x32\x15.ReunionPrivilegeInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReunionPrivilegeChangeNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_REUNIONPRIVILEGECHANGENOTIFY']._serialized_start=66
  _globals['_REUNIONPRIVILEGECHANGENOTIFY']._serialized_end=142
# @@protoc_insertion_point(module_scope)
