# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueDiaryTiredAvatarNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueDiaryAvatar_pb2 as RogueDiaryAvatar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!RogueDiaryTiredAvatarNotify.proto\x1a\x16RogueDiaryAvatar.proto\"\x9f\x01\n\x1bRogueDiaryTiredAvatarNotify\x12\x12\n\nisNeedShow\x18\x0c \x01(\x08\x12\x1b\n\x13Unk3300_BGEJGLBMFII\x18\n \x01(\r\x12\x1b\n\x13Unk3300_DMEMBBPEIGK\x18\x08 \x01(\r\x12\x32\n\x17optionalTiredAvatarList\x18\x0f \x03(\x0b\x32\x11.RogueDiaryAvatarB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueDiaryTiredAvatarNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ROGUEDIARYTIREDAVATARNOTIFY']._serialized_start=62
  _globals['_ROGUEDIARYTIREDAVATARNOTIFY']._serialized_end=221
# @@protoc_insertion_point(module_scope)
