# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueSwitchAvatarRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aRogueSwitchAvatarRsp.proto\"\xa1\x01\n\x14RogueSwitchAvatarRsp\x12\x1f\n\x17\x62\x61\x63kstageAvatarGuidList\x18\x02 \x03(\x04\x12\x1d\n\x15onstageAvatarGuidList\x18\r \x03(\x04\x12\x0e\n\x06\x63\x65llId\x18\x0c \x01(\r\x12\x15\n\rcurAvatarGuid\x18\x03 \x01(\x04\x12\x0f\n\x07retcode\x18\x0f \x01(\x05\x12\x11\n\tdungeonId\x18\x07 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueSwitchAvatarRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ROGUESWITCHAVATARRSP']._serialized_start=31
  _globals['_ROGUESWITCHAVATARRSP']._serialized_end=192
# @@protoc_insertion_point(module_scope)
