# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SalvagePreventSettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SalvagePreventSettleInfo_pb2 as SalvagePreventSettleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n SalvagePreventSettleNotify.proto\x1a\x1eSalvagePreventSettleInfo.proto\"^\n\x1aSalvagePreventSettleNotify\x12\x11\n\tgalleryId\x18\x05 \x01(\r\x12-\n\nsettleInfo\x18\x06 \x01(\x0b\x32\x19.SalvagePreventSettleInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SalvagePreventSettleNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_SALVAGEPREVENTSETTLENOTIFY']._serialized_start=68
  _globals['_SALVAGEPREVENTSETTLENOTIFY']._serialized_end=162
# @@protoc_insertion_point(module_scope)
