# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SalvagePreventStopReason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSalvagePreventStopReason.proto*\xff\x01\n\x18SalvagePreventStopReason\x12\x1d\n\x19SALVAGE_PREVENT_STOP_NONE\x10\x00\x12 \n\x1cSALVAGE_PREVENT_STOP_SUCCESS\x10\x01\x12 \n\x1cSALVAGE_PREVENT_STOP_ARRIVAL\x10\x02\x12\"\n\x1eSALVAGE_PREVENT_STOP_INTERRUPT\x10\x03\x12\x1e\n\x1aSALVAGE_PREVENT_STOP_LEAVE\x10\x04\x12\x1d\n\x19SALVAGE_PREVENT_STOP_FULL\x10\x05\x12\x1d\n\x19SALVAGE_PREVENT_STOP_AWAY\x10\x06\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SalvagePreventStopReason_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_SALVAGEPREVENTSTOPREASON']._serialized_start=35
  _globals['_SALVAGEPREVENTSTOPREASON']._serialized_end=290
# @@protoc_insertion_point(module_scope)
