# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneGalleryFallInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FallPlayerInfo_pb2 as FallPlayerInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSceneGalleryFallInfo.proto\x1a\x14\x46\x61llPlayerInfo.proto\"\xcf\x01\n\x14SceneGalleryFallInfo\x12\x10\n\x08\x65nd_time\x18\x0e \x01(\r\x12U\n\x1ascene_player_fall_info_map\x18\x07 \x03(\x0b\x32\x31.SceneGalleryFallInfo.ScenePlayerFallInfoMapEntry\x1aN\n\x1bScenePlayerFallInfoMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.FallPlayerInfo:\x02\x38\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneGalleryFallInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _SCENEGALLERYFALLINFO_SCENEPLAYERFALLINFOMAPENTRY._options = None
  _SCENEGALLERYFALLINFO_SCENEPLAYERFALLINFOMAPENTRY._serialized_options = b'8\001'
  _globals['_SCENEGALLERYFALLINFO']._serialized_start=53
  _globals['_SCENEGALLERYFALLINFO']._serialized_end=260
  _globals['_SCENEGALLERYFALLINFO_SCENEPLAYERFALLINFOMAPENTRY']._serialized_start=182
  _globals['_SCENEGALLERYFALLINFO_SCENEPLAYERFALLINFOMAPENTRY']._serialized_end=260
# @@protoc_insertion_point(module_scope)
