# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneEntityDisappearNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VisionType_pb2 as VisionType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n SceneEntityDisappearNotify.proto\x1a\x10VisionType.proto\"e\n\x1aSceneEntityDisappearNotify\x12\r\n\x05param\x18\x0f \x01(\r\x12\x13\n\x0b\x65ntity_list\x18\x0e \x03(\r\x12#\n\x0e\x64isappear_type\x18\x08 \x01(\x0e\x32\x0b.VisionTypeB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneEntityDisappearNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_SCENEENTITYDISAPPEARNOTIFY']._serialized_start=54
  _globals['_SCENEENTITYDISAPPEARNOTIFY']._serialized_end=155
# @@protoc_insertion_point(module_scope)
