# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneGallerySalvageEscortInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#SceneGallerySalvageEscortInfo.proto\"u\n\x1dSceneGallerySalvageEscortInfo\x12\x13\n\x0bMKKAIDDJNIJ\x18\r \x01(\r\x12\x13\n\x0bNDNKENCFHPK\x18\x06 \x01(\r\x12\x13\n\x0b\x44PIPHICOICA\x18\x07 \x01(\r\x12\x15\n\rmonster_count\x18\t \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneGallerySalvageEscortInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_SCENEGALLERYSALVAGEESCORTINFO']._serialized_start=39
  _globals['_SCENEGALLERYSALVAGEESCORTINFO']._serialized_end=156
# @@protoc_insertion_point(module_scope)
