# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ScenePlayerLocationNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VehicleLocationInfo_pb2 as VehicleLocationInfo__pb2
import PlayerLocationInfo_pb2 as PlayerLocationInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fScenePlayerLocationNotify.proto\x1a\x19VehicleLocationInfo.proto\x1a\x18PlayerLocationInfo.proto\"\x86\x01\n\x19ScenePlayerLocationNotify\x12\x0f\n\x07sceneId\x18\x01 \x01(\r\x12,\n\x0evehicleLocList\x18\x03 \x03(\x0b\x32\x14.VehicleLocationInfo\x12*\n\rplayerLocList\x18\x0c \x03(\x0b\x32\x13.PlayerLocationInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ScenePlayerLocationNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_SCENEPLAYERLOCATIONNOTIFY']._serialized_start=89
  _globals['_SCENEPLAYERLOCATIONNOTIFY']._serialized_end=223
# @@protoc_insertion_point(module_scope)
