# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServerBuffChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ServerBuff_pb2 as ServerBuff__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cServerBuffChangeNotify.proto\x1a\x10ServerBuff.proto\"\x9c\x02\n\x16ServerBuffChangeNotify\x12M\n\x17server_buff_change_type\x18\x08 \x01(\x0e\x32,.ServerBuffChangeNotify.ServerBuffChangeType\x12\x18\n\x10\x61vatar_guid_list\x18\x05 \x03(\x04\x12%\n\x10server_buff_list\x18\t \x03(\x0b\x32\x0b.ServerBuff\x12\x16\n\x0e\x65ntity_id_list\x18\x0f \x03(\r\x12\x18\n\x10is_creature_buff\x18\x07 \x01(\x08\"@\n\x14ServerBuffChangeType\x12\x13\n\x0f\x41\x44\x44_SERVER_BUFF\x10\x00\x12\x13\n\x0f\x44\x45L_SERVER_BUFF\x10\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ServerBuffChangeNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_SERVERBUFFCHANGENOTIFY']._serialized_start=51
  _globals['_SERVERBUFFCHANGENOTIFY']._serialized_end=335
  _globals['_SERVERBUFFCHANGENOTIFY_SERVERBUFFCHANGETYPE']._serialized_start=271
  _globals['_SERVERBUFFCHANGENOTIFY_SERVERBUFFCHANGETYPE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
