# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetEntityClientDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EntityClientData_pb2 as EntityClientData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSetEntityClientDataNotify.proto\x1a\x16\x45ntityClientData.proto\"]\n\x19SetEntityClientDataNotify\x12-\n\x12\x65ntity_client_data\x18\x0e \x01(\x0b\x32\x11.EntityClientData\x12\x11\n\tentity_id\x18\x07 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetEntityClientDataNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_SETENTITYCLIENTDATANOTIFY']._serialized_start=59
  _globals['_SETENTITYCLIENTDATANOTIFY']._serialized_end=152
# @@protoc_insertion_point(module_scope)
