# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SkillLimitsChange.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GCGCardSkillLimitsInfo_pb2 as GCGCardSkillLimitsInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17SkillLimitsChange.proto\x1a\x1cGCGCardSkillLimitsInfo.proto\"\xb2\x01\n\x11SkillLimitsChange\x12H\n\x13\x63\x61rdLimitsChangeMap\x18\r \x03(\x0b\x32+.SkillLimitsChange.CardLimitsChangeMapEntry\x1aS\n\x18\x43\x61rdLimitsChangeMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.GCGCardSkillLimitsInfo:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SkillLimitsChange_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _SKILLLIMITSCHANGE_CARDLIMITSCHANGEMAPENTRY._options = None
  _SKILLLIMITSCHANGE_CARDLIMITSCHANGEMAPENTRY._serialized_options = b'8\001'
  _globals['_SKILLLIMITSCHANGE']._serialized_start=58
  _globals['_SKILLLIMITSCHANGE']._serialized_end=236
  _globals['_SKILLLIMITSCHANGE_CARDLIMITSCHANGEMAPENTRY']._serialized_start=153
  _globals['_SKILLLIMITSCHANGE_CARDLIMITSCHANGEMAPENTRY']._serialized_end=236
# @@protoc_insertion_point(module_scope)
