# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpiceActivityGivingRecordNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%SpiceActivityGivingRecordNotify.proto\"^\n\x1fSpiceActivityGivingRecordNotify\x12\x13\n\x0bOFGCHEAEEAG\x18\x07 \x01(\r\x12\x11\n\tavatar_id\x18\x0c \x01(\r\x12\x13\n\x0bOCLAPMEFLPK\x18\x0b \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SpiceActivityGivingRecordNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_SPICEACTIVITYGIVINGRECORDNOTIFY']._serialized_start=41
  _globals['_SPICEACTIVITYGIVINGRECORDNOTIFY']._serialized_end=135
# @@protoc_insertion_point(module_scope)
