# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SummerTimeV2BoatSettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SummerTimeV2BoatGallerySettleInfo_pb2 as SummerTimeV2BoatGallerySettleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"SummerTimeV2BoatSettleNotify.proto\x1a\'SummerTimeV2BoatGallerySettleInfo.proto\"\x94\x01\n\x1cSummerTimeV2BoatSettleNotify\x12\x10\n\x08stage_id\x18\t \x01(\r\x12\x37\n\x0bsettle_info\x18\x08 \x01(\x0b\x32\".SummerTimeV2BoatGallerySettleInfo\x12\x12\n\ngallery_id\x18\x0b \x01(\r\x12\x15\n\ris_new_record\x18\n \x01(\x08\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SummerTimeV2BoatSettleNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_SUMMERTIMEV2BOATSETTLENOTIFY']._serialized_start=80
  _globals['_SUMMERTIMEV2BOATSETTLENOTIFY']._serialized_end=228
# @@protoc_insertion_point(module_scope)
