# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SumoSaveTeamReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SumoTeamData_pb2 as SumoTeamData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15SumoSaveTeamReq.proto\x1a\x12SumoTeamData.proto\"m\n\x0fSumoSaveTeamReq\x12\x14\n\x0c\x64ifficultyId\x18\x0e \x01(\r\x12\x1f\n\x08teamList\x18\x02 \x03(\x0b\x32\r.SumoTeamData\x12\x0f\n\x07stageId\x18\x07 \x01(\r\x12\x12\n\nactivityId\x18\x0c \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SumoSaveTeamReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_SUMOSAVETEAMREQ']._serialized_start=45
  _globals['_SUMOSAVETEAMREQ']._serialized_end=154
# @@protoc_insertion_point(module_scope)
