# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeReunionFirstGiftRewardRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#TakeReunionFirstGiftRewardRsp.proto\"C\n\x1dTakeReunionFirstGiftRewardRsp\x12\x11\n\treward_id\x18\x06 \x01(\x05\x12\x0f\n\x07retcode\x18\x04 \x01(\x05\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TakeReunionFirstGiftRewardRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_TAKEREUNIONFIRSTGIFTREWARDRSP']._serialized_start=39
  _globals['_TAKEREUNIONFIRSTGIFTREWARDRSP']._serialized_end=106
# @@protoc_insertion_point(module_scope)
