# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeBattlePassRewardReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattlePassRewardTakeOption_pb2 as BattlePassRewardTakeOption__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dTakeBattlePassRewardReq.proto\x1a BattlePassRewardTakeOption.proto\"N\n\x17TakeBattlePassRewardReq\x12\x33\n\x0etakeOptionList\x18\x01 \x03(\x0b\x32\x1b.BattlePassRewardTakeOptionB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TakeBattlePassRewardReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_TAKEBATTLEPASSREWARDREQ']._serialized_start=67
  _globals['_TAKEBATTLEPASSREWARDREQ']._serialized_end=145
# @@protoc_insertion_point(module_scope)
