# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TowerLevelEndNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemParam_pb2 as ItemParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19TowerLevelEndNotify.proto\x1a\x0fItemParam.proto\"\x80\x02\n\x13TowerLevelEndNotify\x12\x13\n\x0bNHCHEMOAFPB\x18\x0b \x01(\r\x12\x1f\n\x17\x66inished_star_cond_list\x18\r \x03(\r\x12$\n\x10reward_item_list\x18\t \x03(\x0b\x32\n.ItemParam\x12\x13\n\x0bMILBJCPGNJN\x18\x08 \x01(\r\x12\x12\n\nis_success\x18\x07 \x01(\x08\"d\n\x0b\x44\x41MKMDIILDC\x12\x1b\n\x17\x44\x41MKMDIILDC_HNAFLAMPOCO\x10\x00\x12\x1b\n\x17\x44\x41MKMDIILDC_KOCOFDKMJJK\x10\x01\x12\x1b\n\x17\x44\x41MKMDIILDC_NMKCIJMAPGD\x10\x02\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TowerLevelEndNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_TOWERLEVELENDNOTIFY']._serialized_start=47
  _globals['_TOWERLEVELENDNOTIFY']._serialized_end=303
  _globals['_TOWERLEVELENDNOTIFY_DAMKMDIILDC']._serialized_start=203
  _globals['_TOWERLEVELENDNOTIFY_DAMKMDIILDC']._serialized_end=303
# @@protoc_insertion_point(module_scope)
