# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TryEnterHomeReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15TryEnterHomeReq.proto\"X\n\x0fTryEnterHomeReq\x12\x13\n\x0btargetPoint\x18\x0b \x01(\r\x12\x1d\n\x15isTransferToSafePoint\x18\x04 \x01(\x08\x12\x11\n\ttargetUid\x18\x06 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TryEnterHomeReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_TRYENTERHOMEREQ']._serialized_start=25
  _globals['_TRYENTERHOMEREQ']._serialized_end=113
# @@protoc_insertion_point(module_scope)
