# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VintageMarketInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VintageMarketDealInfo_pb2 as VintageMarketDealInfo__pb2
import VintageMarketStoreInfo_pb2 as VintageMarketStoreInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17VintageMarketInfo.proto\x1a\x1bVintageMarketDealInfo.proto\x1a\x1cVintageMarketStoreInfo.proto\"\x80\x06\n\x11VintageMarketInfo\x12\x1a\n\x12unlockStrategyList\x18\x0f \x03(\r\x12\x12\n\nstoreRound\x18\x02 \x01(\r\x12\x1c\n\x13Unk3300_COKBOKAOCNJ\x18\xc0\t \x03(\r\x12>\n\x0e\x62\x61rgainInfoMap\x18\t \x03(\x0b\x32&.VintageMarketInfo.BargainInfoMapEntry\x12\x1b\n\x13Unk3300_ABHHACBDCFI\x18\x03 \x03(\r\x12\x1b\n\x13Unk3300_EDBJLBICEJF\x18\x01 \x03(\r\x12\x1b\n\x13Unk3300_KJDEFIBKBPE\x18\x05 \x01(\x08\x12\x1c\n\x13Unk3300_NMHHGNPKBEL\x18\x8c\t \x01(\x08\x12\x1c\n\x13Unk3300_FOPKAIIAMFM\x18\xff\x01 \x01(\r\x12\x1b\n\x13Unk3300_LMNLHHPMAMN\x18\x0c \x01(\r\x12\x1c\n\x13Unk3300_ALHLENELIEO\x18\x8b\x08 \x01(\x08\x12\x1b\n\x13Unk3300_PAMKPAOCJJJ\x18\x04 \x01(\x08\x12\x1b\n\x13Unk3300_ICJOCDGLFFD\x18\n \x01(\x08\x12(\n\x08\x64\x65\x61lInfo\x18\x0e \x01(\x0b\x32\x16.VintageMarketDealInfo\x12\x1b\n\x13Unk3300_NDFHAGHBCFN\x18\x06 \x01(\x08\x12.\n\ropenStoreList\x18\x07 \x03(\x0b\x32\x17.VintageMarketStoreInfo\x12\x1b\n\x13Unk3300_AIAMBBODLBO\x18\r \x03(\r\x12\x14\n\x0bhelpSkillId\x18\xc6\t \x01(\r\x12\x1b\n\x13Unk3300_FJDIMCJEAOB\x18\x08 \x01(\x08\x12\x1b\n\x13Unk3300_HHKKEDDIGLA\x18\x0b \x01(\r\x12\x1c\n\x13Unk3300_ACJLANLBCGK\x18\xca\x03 \x01(\r\x12\x1c\n\x13Unk3300_NBNOJJBNJPB\x18\xa6\t \x01(\x08\x1a\x35\n\x13\x42\x61rgainInfoMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VintageMarketInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _VINTAGEMARKETINFO_BARGAININFOMAPENTRY._options = None
  _VINTAGEMARKETINFO_BARGAININFOMAPENTRY._serialized_options = b'8\001'
  _globals['_VINTAGEMARKETINFO']._serialized_start=87
  _globals['_VINTAGEMARKETINFO']._serialized_end=855
  _globals['_VINTAGEMARKETINFO_BARGAININFOMAPENTRY']._serialized_start=802
  _globals['_VINTAGEMARKETINFO_BARGAININFOMAPENTRY']._serialized_end=855
# @@protoc_insertion_point(module_scope)
