# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VintageHuntingInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FirstStageInfo_pb2 as FirstStageInfo__pb2
import SecondStageInfo_pb2 as SecondStageInfo__pb2
import ThirdStageInfo_pb2 as ThirdStageInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18VintageHuntingInfo.proto\x1a\x14\x46irstStageInfo.proto\x1a\x15SecondStageInfo.proto\x1a\x14ThirdStageInfo.proto\"\xb6\x01\n\x12VintageHuntingInfo\x12\x0f\n\x07stageId\x18\x02 \x01(\r\x12+\n\x10\x66irst_stage_info\x18\x0e \x01(\x0b\x32\x0f.FirstStageInfoH\x00\x12-\n\x11second_stage_info\x18\x0b \x01(\x0b\x32\x10.SecondStageInfoH\x00\x12+\n\x10third_stage_info\x18\t \x01(\x0b\x32\x0f.ThirdStageInfoH\x00\x42\x06\n\x04infoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VintageHuntingInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_VINTAGEHUNTINGINFO']._serialized_start=96
  _globals['_VINTAGEHUNTINGINFO']._serialized_end=278
# @@protoc_insertion_point(module_scope)
