# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WIDGET_EXTRA_CD_TYPE.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aWIDGET_EXTRA_CD_TYPE.proto*^\n\x14WIDGET_EXTRA_CD_TYPE\x12\x1d\n\x19WIDGET_EXTRA_CD_TYPE_NONE\x10\x00\x12\'\n#WIDGET_EXTRA_CD_TYPE_E_SKILL_SHARED\x10\x01\x42\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WIDGET_EXTRA_CD_TYPE_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_WIDGET_EXTRA_CD_TYPE']._serialized_start=30
  _globals['_WIDGET_EXTRA_CD_TYPE']._serialized_end=124
# @@protoc_insertion_point(module_scope)
