# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WidgetUpdateExtraCDReq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WidgetExtraCdType_pb2 as WidgetExtraCdType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cWidgetUpdateExtraCDReq.proto\x1a\x17WidgetExtraCdType.proto\"f\n\x16WidgetUpdateExtraCDReq\x12\'\n\x0b\x65xtraCdType\x18\t \x01(\x0e\x32\x12.WidgetExtraCdType\x12\x12\n\nmaterialId\x18\x0b \x01(\r\x12\x0f\n\x07\x63\x64Group\x18\x07 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WidgetUpdateExtraCDReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_WIDGETUPDATEEXTRACDREQ']._serialized_start=57
  _globals['_WIDGETUPDATEEXTRACDREQ']._serialized_end=159
# @@protoc_insertion_point(module_scope)
