# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WidgetUpdateExtraCDRsp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WidgetCoolDownData_pb2 as WidgetCoolDownData__pb2
import WidgetExtraCdType_pb2 as WidgetExtraCdType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cWidgetUpdateExtraCDRsp.proto\x1a\x18WidgetCoolDownData.proto\x1a\x17WidgetExtraCdType.proto\"\x9e\x01\n\x16WidgetUpdateExtraCDRsp\x12\x12\n\nmaterialId\x18\x0c \x01(\r\x12\x0f\n\x07\x63\x64Group\x18\x03 \x01(\r\x12%\n\x08\x63oolData\x18\x06 \x01(\x0b\x32\x13.WidgetCoolDownData\x12\x0f\n\x07retcode\x18\r \x01(\x05\x12\'\n\x0b\x65xtraCdType\x18\x04 \x01(\x0e\x32\x12.WidgetExtraCdTypeB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WidgetUpdateExtraCDRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_WIDGETUPDATEEXTRACDRSP']._serialized_start=84
  _globals['_WIDGETUPDATEEXTRACDRSP']._serialized_end=242
# @@protoc_insertion_point(module_scope)
