# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WindFieldGalleryInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n WindFieldGalleryInfoNotify.proto\"\xc4\x01\n\x1aWindFieldGalleryInfoNotify\x12\x13\n\x0b\x42PFKPEOHJHO\x18\x07 \x01(\r\x12\x13\n\x0bLFGKBLLGBBO\x18\x01 \x01(\r\x12\x13\n\x0bIFCFDJKPPEJ\x18\x0e \x01(\r\x12\x13\n\x0bPBABFGGNMDF\x18\x02 \x01(\r\x12\x13\n\x0bLMICEFBKOID\x18\x0b \x01(\r\x12\x13\n\x0bNACBICBMNFJ\x18\x0f \x01(\r\x12\x13\n\x0b\x44PLICOODJLA\x18\x0c \x01(\r\x12\x13\n\x0bJPIIACAHIFE\x18\x04 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WindFieldGalleryInfoNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_WINDFIELDGALLERYINFONOTIFY']._serialized_start=37
  _globals['_WINDFIELDGALLERYINFONOTIFY']._serialized_end=233
# @@protoc_insertion_point(module_scope)
