# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorldRoutineInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16WorldRoutineInfo.proto\"f\n\x10WorldRoutineInfo\x12\x13\n\x0bis_finished\x18\n \x01(\x08\x12\x12\n\nroutine_id\x18\x0f \x01(\r\x12\x10\n\x08progress\x18\t \x01(\r\x12\x17\n\x0f\x66inish_progress\x18\x06 \x01(\rB\x13\n\x11layla.sleep.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WorldRoutineInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021layla.sleep.proto'
  _globals['_WORLDROUTINEINFO']._serialized_start=26
  _globals['_WORLDROUTINEINFO']._serialized_end=128
# @@protoc_insertion_point(module_scope)
